// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.8
// source: guide/guide.proto

package guide

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LikeClockingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClockingId int64  `protobuf:"varint,1,opt,name=clocking_id,json=clockingId,proto3" json:"clocking_id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *LikeClockingReq) Reset() {
	*x = LikeClockingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeClockingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeClockingReq) ProtoMessage() {}

func (x *LikeClockingReq) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeClockingReq.ProtoReflect.Descriptor instead.
func (*LikeClockingReq) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{0}
}

func (x *LikeClockingReq) GetClockingId() int64 {
	if x != nil {
		return x.ClockingId
	}
	return 0
}

func (x *LikeClockingReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LikeClockingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LikeClockingResp) Reset() {
	*x = LikeClockingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeClockingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeClockingResp) ProtoMessage() {}

func (x *LikeClockingResp) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeClockingResp.ProtoReflect.Descriptor instead.
func (*LikeClockingResp) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{1}
}

// 标签
type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId   int32  `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	TagName string `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetTagId() int32 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *Tag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

// 地点
type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foreign      bool   `protobuf:"varint,1,opt,name=foreign,proto3" json:"foreign,omitempty"`
	PositionType int32  `protobuf:"varint,2,opt,name=position_type,json=positionType,proto3" json:"position_type,omitempty"`
	Lon          string `protobuf:"bytes,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat          string `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Nation       string `protobuf:"bytes,5,opt,name=nation,proto3" json:"nation,omitempty"`
	Province     string `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`
	City         string `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	County       string `protobuf:"bytes,8,opt,name=county,proto3" json:"county,omitempty"`
	Town         string `protobuf:"bytes,9,opt,name=town,proto3" json:"town,omitempty"`
	Address      string `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	FlyToHeight  int64  `protobuf:"varint,11,opt,name=fly_to_height,json=flyToHeight,proto3" json:"fly_to_height,omitempty"`
	Distance     int64  `protobuf:"varint,12,opt,name=distance,proto3" json:"distance,omitempty"`
	ShowAddress  string `protobuf:"bytes,13,opt,name=show_address,json=showAddress,proto3" json:"show_address,omitempty"`
	Continent    string `protobuf:"bytes,14,opt,name=continent,proto3" json:"continent,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{3}
}

func (x *Position) GetForeign() bool {
	if x != nil {
		return x.Foreign
	}
	return false
}

func (x *Position) GetPositionType() int32 {
	if x != nil {
		return x.PositionType
	}
	return 0
}

func (x *Position) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *Position) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *Position) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

func (x *Position) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Position) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Position) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

func (x *Position) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *Position) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Position) GetFlyToHeight() int64 {
	if x != nil {
		return x.FlyToHeight
	}
	return 0
}

func (x *Position) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Position) GetShowAddress() string {
	if x != nil {
		return x.ShowAddress
	}
	return ""
}

func (x *Position) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

// 图片
type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Thumb  string `protobuf:"bytes,2,opt,name=thumb,proto3" json:"thumb,omitempty"`
	Width  int64  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height int64  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetThumb() string {
	if x != nil {
		return x.Thumb
	}
	return ""
}

func (x *Image) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ClockingDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClockingId    int64     `protobuf:"varint,1,opt,name=clocking_id,json=clockingId,proto3" json:"clocking_id,omitempty"`
	ClockingTitle string    `protobuf:"bytes,2,opt,name=clocking_title,json=clockingTitle,proto3" json:"clocking_title,omitempty"`
	CoverUrl      *Image    `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	MediaType     int32     `protobuf:"varint,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	UserId        string    `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string    `protobuf:"bytes,6,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserAvatar    string    `protobuf:"bytes,7,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	IsV           bool      `protobuf:"varint,8,opt,name=is_v,json=isV,proto3" json:"is_v,omitempty"`
	ViewNum       int64     `protobuf:"varint,9,opt,name=view_num,json=viewNum,proto3" json:"view_num,omitempty"`
	LikeNum       int64     `protobuf:"varint,10,opt,name=like_num,json=likeNum,proto3" json:"like_num,omitempty"`
	IsLike        bool      `protobuf:"varint,11,opt,name=is_like,json=isLike,proto3" json:"is_like,omitempty"`
	Position      *Position `protobuf:"bytes,12,opt,name=position,proto3" json:"position,omitempty"`
	FirstTag      *Tag      `protobuf:"bytes,13,opt,name=first_tag,json=firstTag,proto3" json:"first_tag,omitempty"`
	PublishTime   string    `protobuf:"bytes,14,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	VideoDuration string    `protobuf:"bytes,15,opt,name=video_duration,json=videoDuration,proto3" json:"video_duration,omitempty"`
	PublishState  int32     `protobuf:"varint,16,opt,name=publish_state,json=publishState,proto3" json:"publish_state,omitempty"`
	State         int32     `protobuf:"varint,17,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ClockingDetail) Reset() {
	*x = ClockingDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClockingDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockingDetail) ProtoMessage() {}

func (x *ClockingDetail) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockingDetail.ProtoReflect.Descriptor instead.
func (*ClockingDetail) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{5}
}

func (x *ClockingDetail) GetClockingId() int64 {
	if x != nil {
		return x.ClockingId
	}
	return 0
}

func (x *ClockingDetail) GetClockingTitle() string {
	if x != nil {
		return x.ClockingTitle
	}
	return ""
}

func (x *ClockingDetail) GetCoverUrl() *Image {
	if x != nil {
		return x.CoverUrl
	}
	return nil
}

func (x *ClockingDetail) GetMediaType() int32 {
	if x != nil {
		return x.MediaType
	}
	return 0
}

func (x *ClockingDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClockingDetail) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ClockingDetail) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *ClockingDetail) GetIsV() bool {
	if x != nil {
		return x.IsV
	}
	return false
}

func (x *ClockingDetail) GetViewNum() int64 {
	if x != nil {
		return x.ViewNum
	}
	return 0
}

func (x *ClockingDetail) GetLikeNum() int64 {
	if x != nil {
		return x.LikeNum
	}
	return 0
}

func (x *ClockingDetail) GetIsLike() bool {
	if x != nil {
		return x.IsLike
	}
	return false
}

func (x *ClockingDetail) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ClockingDetail) GetFirstTag() *Tag {
	if x != nil {
		return x.FirstTag
	}
	return nil
}

func (x *ClockingDetail) GetPublishTime() string {
	if x != nil {
		return x.PublishTime
	}
	return ""
}

func (x *ClockingDetail) GetVideoDuration() string {
	if x != nil {
		return x.VideoDuration
	}
	return ""
}

func (x *ClockingDetail) GetPublishState() int32 {
	if x != nil {
		return x.PublishState
	}
	return 0
}

func (x *ClockingDetail) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type MGetClockingDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids    []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	UserId string  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lon    string  `protobuf:"bytes,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat    string  `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *MGetClockingDetailReq) Reset() {
	*x = MGetClockingDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MGetClockingDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetClockingDetailReq) ProtoMessage() {}

func (x *MGetClockingDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetClockingDetailReq.ProtoReflect.Descriptor instead.
func (*MGetClockingDetailReq) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{6}
}

func (x *MGetClockingDetailReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *MGetClockingDetailReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MGetClockingDetailReq) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *MGetClockingDetailReq) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

type MGetClockingDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docs []*ClockingDetail `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
}

func (x *MGetClockingDetailResp) Reset() {
	*x = MGetClockingDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MGetClockingDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetClockingDetailResp) ProtoMessage() {}

func (x *MGetClockingDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetClockingDetailResp.ProtoReflect.Descriptor instead.
func (*MGetClockingDetailResp) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{7}
}

func (x *MGetClockingDetailResp) GetDocs() []*ClockingDetail {
	if x != nil {
		return x.Docs
	}
	return nil
}

type LandscapeViewDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LandscapeId      int64     `protobuf:"varint,1,opt,name=landscape_id,json=landscapeId,proto3" json:"landscape_id,omitempty"`
	LandscapeName    string    `protobuf:"bytes,2,opt,name=landscape_name,json=landscapeName,proto3" json:"landscape_name,omitempty"`
	CoverUrl         string    `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Position         *Position `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	ViewNum          int64     `protobuf:"varint,5,opt,name=view_num,json=viewNum,proto3" json:"view_num,omitempty"`
	CommentPkgSwitch int32     `protobuf:"varint,6,opt,name=comment_pkg_switch,json=commentPkgSwitch,proto3" json:"comment_pkg_switch,omitempty"`
	VrTourSwitch     int32     `protobuf:"varint,7,opt,name=vr_tour_switch,json=vrTourSwitch,proto3" json:"vr_tour_switch,omitempty"`
}

func (x *LandscapeViewDetail) Reset() {
	*x = LandscapeViewDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LandscapeViewDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandscapeViewDetail) ProtoMessage() {}

func (x *LandscapeViewDetail) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandscapeViewDetail.ProtoReflect.Descriptor instead.
func (*LandscapeViewDetail) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{8}
}

func (x *LandscapeViewDetail) GetLandscapeId() int64 {
	if x != nil {
		return x.LandscapeId
	}
	return 0
}

func (x *LandscapeViewDetail) GetLandscapeName() string {
	if x != nil {
		return x.LandscapeName
	}
	return ""
}

func (x *LandscapeViewDetail) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *LandscapeViewDetail) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *LandscapeViewDetail) GetViewNum() int64 {
	if x != nil {
		return x.ViewNum
	}
	return 0
}

func (x *LandscapeViewDetail) GetCommentPkgSwitch() int32 {
	if x != nil {
		return x.CommentPkgSwitch
	}
	return 0
}

func (x *LandscapeViewDetail) GetVrTourSwitch() int32 {
	if x != nil {
		return x.VrTourSwitch
	}
	return 0
}

type MGetLandscapeViewDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids    []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	UserId string  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lon    string  `protobuf:"bytes,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat    string  `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
}

func (x *MGetLandscapeViewDetailReq) Reset() {
	*x = MGetLandscapeViewDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MGetLandscapeViewDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetLandscapeViewDetailReq) ProtoMessage() {}

func (x *MGetLandscapeViewDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetLandscapeViewDetailReq.ProtoReflect.Descriptor instead.
func (*MGetLandscapeViewDetailReq) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{9}
}

func (x *MGetLandscapeViewDetailReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *MGetLandscapeViewDetailReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MGetLandscapeViewDetailReq) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *MGetLandscapeViewDetailReq) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

type MGetLandscapeViewDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docs []*LandscapeViewDetail `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
}

func (x *MGetLandscapeViewDetailResp) Reset() {
	*x = MGetLandscapeViewDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_guide_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MGetLandscapeViewDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetLandscapeViewDetailResp) ProtoMessage() {}

func (x *MGetLandscapeViewDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_guide_guide_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetLandscapeViewDetailResp.ProtoReflect.Descriptor instead.
func (*MGetLandscapeViewDetailResp) Descriptor() ([]byte, []int) {
	return file_guide_guide_proto_rawDescGZIP(), []int{10}
}

func (x *MGetLandscapeViewDetailResp) GetDocs() []*LandscapeViewDetail {
	if x != nil {
		return x.Docs
	}
	return nil
}

var File_guide_guide_proto protoreflect.FileDescriptor

var file_guide_guide_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2f, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0f, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6c, 0x6f, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6c, 0x6f,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x37, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x74,
	0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x61, 0x67,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xfc, 0x02,
	0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f,
	0x72, 0x65, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x66, 0x6f, 0x72,
	0x65, 0x69, 0x67, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x6f, 0x77, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x77,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x66,
	0x6c, 0x79, 0x5f, 0x74, 0x6f, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x66, 0x6c, 0x79, 0x54, 0x6f, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x68, 0x6f, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x22, 0x5d, 0x0a, 0x05,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x75, 0x6d, 0x62,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0xa4, 0x04, 0x0a, 0x0e,
	0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x09, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x11, 0x0a, 0x04, 0x69, 0x73, 0x5f, 0x76, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x03, 0x69, 0x73, 0x56, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x6e, 0x75, 0x6d,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x12,
	0x19, 0x0a, 0x08, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x6c, 0x69, 0x6b, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73,
	0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c,
	0x69, 0x6b, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e,
	0x54, 0x61, 0x67, 0x52, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x54, 0x61, 0x67, 0x12, 0x21, 0x0a,
	0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x66, 0x0a, 0x15, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x22, 0x3d, 0x0a, 0x16, 0x4d, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x22, 0x92, 0x02, 0x0a, 0x13, 0x4c, 0x61,
	0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x56, 0x69, 0x65, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61,
	0x70, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x61,
	0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x0a, 0x08, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x76, 0x69, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x6b, 0x67, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x50,
	0x6b, 0x67, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x24, 0x0a, 0x0e, 0x76, 0x72, 0x5f, 0x74,
	0x6f, 0x75, 0x72, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x76, 0x72, 0x54, 0x6f, 0x75, 0x72, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x22, 0x6b,
	0x0a, 0x1a, 0x4d, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x56,
	0x69, 0x65, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x22, 0x47, 0x0a, 0x1b, 0x4d,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x56, 0x69, 0x65, 0x77,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x6f,
	0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4c, 0x61, 0x6e, 0x64, 0x73,
	0x63, 0x61, 0x70, 0x65, 0x56, 0x69, 0x65, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x04,
	0x64, 0x6f, 0x63, 0x73, 0x32, 0xe0, 0x01, 0x0a, 0x0c, 0x47, 0x75, 0x69, 0x64, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x12, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x2e, 0x4d, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x4d, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x54, 0x0a, 0x17,
	0x4d, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x56, 0x69, 0x65,
	0x77, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x2e, 0x4d, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x56, 0x69, 0x65, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x4d, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73,
	0x63, 0x61, 0x70, 0x65, 0x56, 0x69, 0x65, 0x77, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x33, 0x0a, 0x0c, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x12, 0x10, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6c, 0x6f, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x67, 0x75, 0x69,
	0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_guide_guide_proto_rawDescOnce sync.Once
	file_guide_guide_proto_rawDescData = file_guide_guide_proto_rawDesc
)

func file_guide_guide_proto_rawDescGZIP() []byte {
	file_guide_guide_proto_rawDescOnce.Do(func() {
		file_guide_guide_proto_rawDescData = protoimpl.X.CompressGZIP(file_guide_guide_proto_rawDescData)
	})
	return file_guide_guide_proto_rawDescData
}

var file_guide_guide_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_guide_guide_proto_goTypes = []interface{}{
	(*LikeClockingReq)(nil),             // 0: LikeClockingReq
	(*LikeClockingResp)(nil),            // 1: LikeClockingResp
	(*Tag)(nil),                         // 2: Tag
	(*Position)(nil),                    // 3: Position
	(*Image)(nil),                       // 4: Image
	(*ClockingDetail)(nil),              // 5: ClockingDetail
	(*MGetClockingDetailReq)(nil),       // 6: MGetClockingDetailReq
	(*MGetClockingDetailResp)(nil),      // 7: MGetClockingDetailResp
	(*LandscapeViewDetail)(nil),         // 8: LandscapeViewDetail
	(*MGetLandscapeViewDetailReq)(nil),  // 9: MGetLandscapeViewDetailReq
	(*MGetLandscapeViewDetailResp)(nil), // 10: MGetLandscapeViewDetailResp
}
var file_guide_guide_proto_depIdxs = []int32{
	4,  // 0: ClockingDetail.cover_url:type_name -> Image
	3,  // 1: ClockingDetail.position:type_name -> Position
	2,  // 2: ClockingDetail.first_tag:type_name -> Tag
	5,  // 3: MGetClockingDetailResp.docs:type_name -> ClockingDetail
	3,  // 4: LandscapeViewDetail.position:type_name -> Position
	8,  // 5: MGetLandscapeViewDetailResp.docs:type_name -> LandscapeViewDetail
	6,  // 6: GuideService.MGetClockingDetail:input_type -> MGetClockingDetailReq
	9,  // 7: GuideService.MGetLandscapeViewDetail:input_type -> MGetLandscapeViewDetailReq
	0,  // 8: GuideService.LikeClocking:input_type -> LikeClockingReq
	7,  // 9: GuideService.MGetClockingDetail:output_type -> MGetClockingDetailResp
	10, // 10: GuideService.MGetLandscapeViewDetail:output_type -> MGetLandscapeViewDetailResp
	1,  // 11: GuideService.LikeClocking:output_type -> LikeClockingResp
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_guide_guide_proto_init() }
func file_guide_guide_proto_init() {
	if File_guide_guide_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_guide_guide_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeClockingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeClockingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClockingDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MGetClockingDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MGetClockingDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LandscapeViewDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MGetLandscapeViewDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_guide_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MGetLandscapeViewDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_guide_guide_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guide_guide_proto_goTypes,
		DependencyIndexes: file_guide_guide_proto_depIdxs,
		MessageInfos:      file_guide_guide_proto_msgTypes,
	}.Build()
	File_guide_guide_proto = out.File
	file_guide_guide_proto_rawDesc = nil
	file_guide_guide_proto_goTypes = nil
	file_guide_guide_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GuideServiceClient is the client API for GuideService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuideServiceClient interface {
	// 批量获取打卡详情
	MGetClockingDetail(ctx context.Context, in *MGetClockingDetailReq, opts ...grpc.CallOption) (*MGetClockingDetailResp, error)
	// 批量获取景区详情
	MGetLandscapeViewDetail(ctx context.Context, in *MGetLandscapeViewDetailReq, opts ...grpc.CallOption) (*MGetLandscapeViewDetailResp, error)
	// 给景区打卡点赞
	LikeClocking(ctx context.Context, in *LikeClockingReq, opts ...grpc.CallOption) (*LikeClockingResp, error)
}

type guideServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuideServiceClient(cc grpc.ClientConnInterface) GuideServiceClient {
	return &guideServiceClient{cc}
}

func (c *guideServiceClient) MGetClockingDetail(ctx context.Context, in *MGetClockingDetailReq, opts ...grpc.CallOption) (*MGetClockingDetailResp, error) {
	out := new(MGetClockingDetailResp)
	err := c.cc.Invoke(ctx, "/GuideService/MGetClockingDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideServiceClient) MGetLandscapeViewDetail(ctx context.Context, in *MGetLandscapeViewDetailReq, opts ...grpc.CallOption) (*MGetLandscapeViewDetailResp, error) {
	out := new(MGetLandscapeViewDetailResp)
	err := c.cc.Invoke(ctx, "/GuideService/MGetLandscapeViewDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guideServiceClient) LikeClocking(ctx context.Context, in *LikeClockingReq, opts ...grpc.CallOption) (*LikeClockingResp, error) {
	out := new(LikeClockingResp)
	err := c.cc.Invoke(ctx, "/GuideService/LikeClocking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuideServiceServer is the server API for GuideService service.
type GuideServiceServer interface {
	// 批量获取打卡详情
	MGetClockingDetail(context.Context, *MGetClockingDetailReq) (*MGetClockingDetailResp, error)
	// 批量获取景区详情
	MGetLandscapeViewDetail(context.Context, *MGetLandscapeViewDetailReq) (*MGetLandscapeViewDetailResp, error)
	// 给景区打卡点赞
	LikeClocking(context.Context, *LikeClockingReq) (*LikeClockingResp, error)
}

// UnimplementedGuideServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGuideServiceServer struct {
}

func (*UnimplementedGuideServiceServer) MGetClockingDetail(context.Context, *MGetClockingDetailReq) (*MGetClockingDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MGetClockingDetail not implemented")
}
func (*UnimplementedGuideServiceServer) MGetLandscapeViewDetail(context.Context, *MGetLandscapeViewDetailReq) (*MGetLandscapeViewDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MGetLandscapeViewDetail not implemented")
}
func (*UnimplementedGuideServiceServer) LikeClocking(context.Context, *LikeClockingReq) (*LikeClockingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeClocking not implemented")
}

func RegisterGuideServiceServer(s *grpc.Server, srv GuideServiceServer) {
	s.RegisterService(&_GuideService_serviceDesc, srv)
}

func _GuideService_MGetClockingDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MGetClockingDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideServiceServer).MGetClockingDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GuideService/MGetClockingDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideServiceServer).MGetClockingDetail(ctx, req.(*MGetClockingDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideService_MGetLandscapeViewDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MGetLandscapeViewDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideServiceServer).MGetLandscapeViewDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GuideService/MGetLandscapeViewDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideServiceServer).MGetLandscapeViewDetail(ctx, req.(*MGetLandscapeViewDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuideService_LikeClocking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeClockingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuideServiceServer).LikeClocking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GuideService/LikeClocking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuideServiceServer).LikeClocking(ctx, req.(*LikeClockingReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuideService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GuideService",
	HandlerType: (*GuideServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MGetClockingDetail",
			Handler:    _GuideService_MGetClockingDetail_Handler,
		},
		{
			MethodName: "MGetLandscapeViewDetail",
			Handler:    _GuideService_MGetLandscapeViewDetail_Handler,
		},
		{
			MethodName: "LikeClocking",
			Handler:    _GuideService_LikeClocking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guide/guide.proto",
}
