// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.1
// source: wetoken/wetoken.proto

package wetoken

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetAccessTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *GetAccessTokenReq) Reset() {
	*x = GetAccessTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wetoken_wetoken_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccessTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenReq) ProtoMessage() {}

func (x *GetAccessTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_wetoken_wetoken_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenReq.ProtoReflect.Descriptor instead.
func (*GetAccessTokenReq) Descriptor() ([]byte, []int) {
	return file_wetoken_wetoken_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccessTokenReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetAccessTokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
}

func (x *GetAccessTokenResp) Reset() {
	*x = GetAccessTokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wetoken_wetoken_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccessTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenResp) ProtoMessage() {}

func (x *GetAccessTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_wetoken_wetoken_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenResp.ProtoReflect.Descriptor instead.
func (*GetAccessTokenResp) Descriptor() ([]byte, []int) {
	return file_wetoken_wetoken_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccessTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_wetoken_wetoken_proto protoreflect.FileDescriptor

var file_wetoken_wetoken_proto_rawDesc = []byte{
	0x0a, 0x15, 0x77, 0x65, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x77, 0x65, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x4b, 0x0a, 0x0e, 0x57,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x12, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x77, 0x65,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wetoken_wetoken_proto_rawDescOnce sync.Once
	file_wetoken_wetoken_proto_rawDescData = file_wetoken_wetoken_proto_rawDesc
)

func file_wetoken_wetoken_proto_rawDescGZIP() []byte {
	file_wetoken_wetoken_proto_rawDescOnce.Do(func() {
		file_wetoken_wetoken_proto_rawDescData = protoimpl.X.CompressGZIP(file_wetoken_wetoken_proto_rawDescData)
	})
	return file_wetoken_wetoken_proto_rawDescData
}

var file_wetoken_wetoken_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wetoken_wetoken_proto_goTypes = []interface{}{
	(*GetAccessTokenReq)(nil),  // 0: GetAccessTokenReq
	(*GetAccessTokenResp)(nil), // 1: GetAccessTokenResp
}
var file_wetoken_wetoken_proto_depIdxs = []int32{
	0, // 0: WeTokenService.GetAccessToken:input_type -> GetAccessTokenReq
	1, // 1: WeTokenService.GetAccessToken:output_type -> GetAccessTokenResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wetoken_wetoken_proto_init() }
func file_wetoken_wetoken_proto_init() {
	if File_wetoken_wetoken_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wetoken_wetoken_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccessTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wetoken_wetoken_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccessTokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wetoken_wetoken_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wetoken_wetoken_proto_goTypes,
		DependencyIndexes: file_wetoken_wetoken_proto_depIdxs,
		MessageInfos:      file_wetoken_wetoken_proto_msgTypes,
	}.Build()
	File_wetoken_wetoken_proto = out.File
	file_wetoken_wetoken_proto_rawDesc = nil
	file_wetoken_wetoken_proto_goTypes = nil
	file_wetoken_wetoken_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WeTokenServiceClient is the client API for WeTokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WeTokenServiceClient interface {
	GetAccessToken(ctx context.Context, in *GetAccessTokenReq, opts ...grpc.CallOption) (*GetAccessTokenResp, error)
}

type weTokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeTokenServiceClient(cc grpc.ClientConnInterface) WeTokenServiceClient {
	return &weTokenServiceClient{cc}
}

func (c *weTokenServiceClient) GetAccessToken(ctx context.Context, in *GetAccessTokenReq, opts ...grpc.CallOption) (*GetAccessTokenResp, error) {
	out := new(GetAccessTokenResp)
	err := c.cc.Invoke(ctx, "/WeTokenService/GetAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeTokenServiceServer is the server API for WeTokenService service.
type WeTokenServiceServer interface {
	GetAccessToken(context.Context, *GetAccessTokenReq) (*GetAccessTokenResp, error)
}

// UnimplementedWeTokenServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWeTokenServiceServer struct {
}

func (*UnimplementedWeTokenServiceServer) GetAccessToken(context.Context, *GetAccessTokenReq) (*GetAccessTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessToken not implemented")
}

func RegisterWeTokenServiceServer(s *grpc.Server, srv WeTokenServiceServer) {
	s.RegisterService(&_WeTokenService_serviceDesc, srv)
}

func _WeTokenService_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeTokenServiceServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WeTokenService/GetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeTokenServiceServer).GetAccessToken(ctx, req.(*GetAccessTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WeTokenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WeTokenService",
	HandlerType: (*WeTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessToken",
			Handler:    _WeTokenService_GetAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wetoken/wetoken.proto",
}
