// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.8.0
// source: stream_sync/stream_sync.proto

package stream_sync

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LiveSourceId int64 `protobuf:"varint,1,opt,name=LiveSourceId,proto3" json:"LiveSourceId,omitempty"`
}

func (x *SyncReq) Reset() {
	*x = SyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stream_sync_stream_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReq) ProtoMessage() {}

func (x *SyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_stream_sync_stream_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReq.ProtoReflect.Descriptor instead.
func (*SyncReq) Descriptor() ([]byte, []int) {
	return file_stream_sync_stream_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncReq) GetLiveSourceId() int64 {
	if x != nil {
		return x.LiveSourceId
	}
	return 0
}

type SyncResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncResp) Reset() {
	*x = SyncResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stream_sync_stream_sync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResp) ProtoMessage() {}

func (x *SyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_stream_sync_stream_sync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResp.ProtoReflect.Descriptor instead.
func (*SyncResp) Descriptor() ([]byte, []int) {
	return file_stream_sync_stream_sync_proto_rawDescGZIP(), []int{1}
}

var File_stream_sync_stream_sync_proto protoreflect.FileDescriptor

var file_stream_sync_stream_sync_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2d, 0x0a, 0x07, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x4c, 0x69,
	0x76, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x0a,
	0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x32, 0x30, 0x0a, 0x11, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x1b, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x08, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x71, 0x1a, 0x09, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d,
	0x2e, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stream_sync_stream_sync_proto_rawDescOnce sync.Once
	file_stream_sync_stream_sync_proto_rawDescData = file_stream_sync_stream_sync_proto_rawDesc
)

func file_stream_sync_stream_sync_proto_rawDescGZIP() []byte {
	file_stream_sync_stream_sync_proto_rawDescOnce.Do(func() {
		file_stream_sync_stream_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_stream_sync_stream_sync_proto_rawDescData)
	})
	return file_stream_sync_stream_sync_proto_rawDescData
}

var file_stream_sync_stream_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stream_sync_stream_sync_proto_goTypes = []interface{}{
	(*SyncReq)(nil),  // 0: SyncReq
	(*SyncResp)(nil), // 1: SyncResp
}
var file_stream_sync_stream_sync_proto_depIdxs = []int32{
	0, // 0: StreamSyncService.Sync:input_type -> SyncReq
	1, // 1: StreamSyncService.Sync:output_type -> SyncResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_sync_stream_sync_proto_init() }
func file_stream_sync_stream_sync_proto_init() {
	if File_stream_sync_stream_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stream_sync_stream_sync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stream_sync_stream_sync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stream_sync_stream_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_sync_stream_sync_proto_goTypes,
		DependencyIndexes: file_stream_sync_stream_sync_proto_depIdxs,
		MessageInfos:      file_stream_sync_stream_sync_proto_msgTypes,
	}.Build()
	File_stream_sync_stream_sync_proto = out.File
	file_stream_sync_stream_sync_proto_rawDesc = nil
	file_stream_sync_stream_sync_proto_goTypes = nil
	file_stream_sync_stream_sync_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StreamSyncServiceClient is the client API for StreamSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamSyncServiceClient interface {
	Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*SyncResp, error)
}

type streamSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamSyncServiceClient(cc grpc.ClientConnInterface) StreamSyncServiceClient {
	return &streamSyncServiceClient{cc}
}

func (c *streamSyncServiceClient) Sync(ctx context.Context, in *SyncReq, opts ...grpc.CallOption) (*SyncResp, error) {
	out := new(SyncResp)
	err := c.cc.Invoke(ctx, "/StreamSyncService/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamSyncServiceServer is the server API for StreamSyncService service.
type StreamSyncServiceServer interface {
	Sync(context.Context, *SyncReq) (*SyncResp, error)
}

// UnimplementedStreamSyncServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStreamSyncServiceServer struct {
}

func (*UnimplementedStreamSyncServiceServer) Sync(context.Context, *SyncReq) (*SyncResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}

func RegisterStreamSyncServiceServer(s *grpc.Server, srv StreamSyncServiceServer) {
	s.RegisterService(&_StreamSyncService_serviceDesc, srv)
}

func _StreamSyncService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamSyncServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StreamSyncService/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamSyncServiceServer).Sync(ctx, req.(*SyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreamSyncService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StreamSyncService",
	HandlerType: (*StreamSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _StreamSyncService_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stream_sync/stream_sync.proto",
}
