// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message_push/message_push.proto

package message_push

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotificationContent_ArticleType int32

const (
	NotificationContent_NoType      NotificationContent_ArticleType = 0
	NotificationContent_Wiki        NotificationContent_ArticleType = 10
	NotificationContent_Ugc         NotificationContent_ArticleType = 20
	NotificationContent_AnchorShare NotificationContent_ArticleType = 30
	NotificationContent_Video       NotificationContent_ArticleType = 40
	NotificationContent_ClockImage  NotificationContent_ArticleType = 60
	NotificationContent_ClockVideo  NotificationContent_ArticleType = 70
)

var NotificationContent_ArticleType_name = map[int32]string{
	0:  "NoType",
	10: "Wiki",
	20: "Ugc",
	30: "AnchorShare",
	40: "Video",
	60: "ClockImage",
	70: "ClockVideo",
}

var NotificationContent_ArticleType_value = map[string]int32{
	"NoType":      0,
	"Wiki":        10,
	"Ugc":         20,
	"AnchorShare": 30,
	"Video":       40,
	"ClockImage":  60,
	"ClockVideo":  70,
}

func (x NotificationContent_ArticleType) String() string {
	return proto.EnumName(NotificationContent_ArticleType_name, int32(x))
}

func (NotificationContent_ArticleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{6, 0}
}

type NotificationContent_Behavior int32

const (
	NotificationContent_NoBehavior          NotificationContent_Behavior = 0
	NotificationContent_BeFollow            NotificationContent_Behavior = 10
	NotificationContent_UgcLiked            NotificationContent_Behavior = 20
	NotificationContent_UgcCollected        NotificationContent_Behavior = 30
	NotificationContent_UgcCommented        NotificationContent_Behavior = 40
	NotificationContent_CommentReplied      NotificationContent_Behavior = 50
	NotificationContent_CommentLiked        NotificationContent_Behavior = 60
	NotificationContent_AuditFailed         NotificationContent_Behavior = 70
	NotificationContent_BeTopicHot          NotificationContent_Behavior = 80
	NotificationContent_VideoCommented      NotificationContent_Behavior = 160
	NotificationContent_ClockImageCommented NotificationContent_Behavior = 230
	NotificationContent_ClockImageLiked     NotificationContent_Behavior = 240
	NotificationContent_ClockVideoCommented NotificationContent_Behavior = 250
	NotificationContent_ClockVideoLiked     NotificationContent_Behavior = 260
)

var NotificationContent_Behavior_name = map[int32]string{
	0:   "NoBehavior",
	10:  "BeFollow",
	20:  "UgcLiked",
	30:  "UgcCollected",
	40:  "UgcCommented",
	50:  "CommentReplied",
	60:  "CommentLiked",
	70:  "AuditFailed",
	80:  "BeTopicHot",
	160: "VideoCommented",
	230: "ClockImageCommented",
	240: "ClockImageLiked",
	250: "ClockVideoCommented",
	260: "ClockVideoLiked",
}

var NotificationContent_Behavior_value = map[string]int32{
	"NoBehavior":          0,
	"BeFollow":            10,
	"UgcLiked":            20,
	"UgcCollected":        30,
	"UgcCommented":        40,
	"CommentReplied":      50,
	"CommentLiked":        60,
	"AuditFailed":         70,
	"BeTopicHot":          80,
	"VideoCommented":      160,
	"ClockImageCommented": 230,
	"ClockImageLiked":     240,
	"ClockVideoCommented": 250,
	"ClockVideoLiked":     260,
}

func (x NotificationContent_Behavior) String() string {
	return proto.EnumName(NotificationContent_Behavior_name, int32(x))
}

func (NotificationContent_Behavior) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{6, 1}
}

type SendPhoneMsgReq struct {
	PhoneList            []string `protobuf:"bytes,1,rep,name=phone_list,json=phoneList,proto3" json:"phone_list,omitempty"`
	TemplateCode         string   `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPhoneMsgReq) Reset()         { *m = SendPhoneMsgReq{} }
func (m *SendPhoneMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendPhoneMsgReq) ProtoMessage()    {}
func (*SendPhoneMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{0}
}

func (m *SendPhoneMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPhoneMsgReq.Unmarshal(m, b)
}
func (m *SendPhoneMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPhoneMsgReq.Marshal(b, m, deterministic)
}
func (m *SendPhoneMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPhoneMsgReq.Merge(m, src)
}
func (m *SendPhoneMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendPhoneMsgReq.Size(m)
}
func (m *SendPhoneMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPhoneMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendPhoneMsgReq proto.InternalMessageInfo

func (m *SendPhoneMsgReq) GetPhoneList() []string {
	if m != nil {
		return m.PhoneList
	}
	return nil
}

func (m *SendPhoneMsgReq) GetTemplateCode() string {
	if m != nil {
		return m.TemplateCode
	}
	return ""
}

type SendPhoneMsgResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPhoneMsgResp) Reset()         { *m = SendPhoneMsgResp{} }
func (m *SendPhoneMsgResp) String() string { return proto.CompactTextString(m) }
func (*SendPhoneMsgResp) ProtoMessage()    {}
func (*SendPhoneMsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{1}
}

func (m *SendPhoneMsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPhoneMsgResp.Unmarshal(m, b)
}
func (m *SendPhoneMsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPhoneMsgResp.Marshal(b, m, deterministic)
}
func (m *SendPhoneMsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPhoneMsgResp.Merge(m, src)
}
func (m *SendPhoneMsgResp) XXX_Size() int {
	return xxx_messageInfo_SendPhoneMsgResp.Size(m)
}
func (m *SendPhoneMsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPhoneMsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendPhoneMsgResp proto.InternalMessageInfo

type UserNotification struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	PushList             []string `protobuf:"bytes,3,rep,name=push_list,json=pushList,proto3" json:"push_list,omitempty"`
	PlatForm             string   `protobuf:"bytes,4,opt,name=plat_form,json=platForm,proto3" json:"plat_form,omitempty"`
	ExtParams            string   `protobuf:"bytes,5,opt,name=ext_params,json=extParams,proto3" json:"ext_params,omitempty"`
	Batch                int32    `protobuf:"varint,6,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserNotification) Reset()         { *m = UserNotification{} }
func (m *UserNotification) String() string { return proto.CompactTextString(m) }
func (*UserNotification) ProtoMessage()    {}
func (*UserNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{2}
}

func (m *UserNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNotification.Unmarshal(m, b)
}
func (m *UserNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNotification.Marshal(b, m, deterministic)
}
func (m *UserNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNotification.Merge(m, src)
}
func (m *UserNotification) XXX_Size() int {
	return xxx_messageInfo_UserNotification.Size(m)
}
func (m *UserNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNotification.DiscardUnknown(m)
}

var xxx_messageInfo_UserNotification proto.InternalMessageInfo

func (m *UserNotification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UserNotification) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *UserNotification) GetPushList() []string {
	if m != nil {
		return m.PushList
	}
	return nil
}

func (m *UserNotification) GetPlatForm() string {
	if m != nil {
		return m.PlatForm
	}
	return ""
}

func (m *UserNotification) GetExtParams() string {
	if m != nil {
		return m.ExtParams
	}
	return ""
}

func (m *UserNotification) GetBatch() int32 {
	if m != nil {
		return m.Batch
	}
	return 0
}

type AppNotificationContent struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ArticleId            string   `protobuf:"bytes,4,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ArticleType          int32    `protobuf:"varint,5,opt,name=article_type,json=articleType,proto3" json:"article_type,omitempty"`
	Cover                string   `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	PlatForm             int32    `protobuf:"varint,7,opt,name=plat_form,json=platForm,proto3" json:"plat_form,omitempty"`
	DeviceToken          string   `protobuf:"bytes,8,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	MessageId            int32    `protobuf:"varint,9,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Reason               int32    `protobuf:"varint,10,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppNotificationContent) Reset()         { *m = AppNotificationContent{} }
func (m *AppNotificationContent) String() string { return proto.CompactTextString(m) }
func (*AppNotificationContent) ProtoMessage()    {}
func (*AppNotificationContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{3}
}

func (m *AppNotificationContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppNotificationContent.Unmarshal(m, b)
}
func (m *AppNotificationContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppNotificationContent.Marshal(b, m, deterministic)
}
func (m *AppNotificationContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppNotificationContent.Merge(m, src)
}
func (m *AppNotificationContent) XXX_Size() int {
	return xxx_messageInfo_AppNotificationContent.Size(m)
}
func (m *AppNotificationContent) XXX_DiscardUnknown() {
	xxx_messageInfo_AppNotificationContent.DiscardUnknown(m)
}

var xxx_messageInfo_AppNotificationContent proto.InternalMessageInfo

func (m *AppNotificationContent) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AppNotificationContent) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *AppNotificationContent) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AppNotificationContent) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

func (m *AppNotificationContent) GetArticleType() int32 {
	if m != nil {
		return m.ArticleType
	}
	return 0
}

func (m *AppNotificationContent) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *AppNotificationContent) GetPlatForm() int32 {
	if m != nil {
		return m.PlatForm
	}
	return 0
}

func (m *AppNotificationContent) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

func (m *AppNotificationContent) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *AppNotificationContent) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

type ActivityNotificationContent struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	DeviceToken          string   `protobuf:"bytes,3,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlatForm             string   `protobuf:"bytes,5,opt,name=plat_form,json=platForm,proto3" json:"plat_form,omitempty"`
	ExtParams            string   `protobuf:"bytes,6,opt,name=ext_params,json=extParams,proto3" json:"ext_params,omitempty"`
	ActivityId           string   `protobuf:"bytes,7,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	NotifyType           int32    `protobuf:"varint,8,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityNotificationContent) Reset()         { *m = ActivityNotificationContent{} }
func (m *ActivityNotificationContent) String() string { return proto.CompactTextString(m) }
func (*ActivityNotificationContent) ProtoMessage()    {}
func (*ActivityNotificationContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{4}
}

func (m *ActivityNotificationContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityNotificationContent.Unmarshal(m, b)
}
func (m *ActivityNotificationContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityNotificationContent.Marshal(b, m, deterministic)
}
func (m *ActivityNotificationContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityNotificationContent.Merge(m, src)
}
func (m *ActivityNotificationContent) XXX_Size() int {
	return xxx_messageInfo_ActivityNotificationContent.Size(m)
}
func (m *ActivityNotificationContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityNotificationContent.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityNotificationContent proto.InternalMessageInfo

func (m *ActivityNotificationContent) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ActivityNotificationContent) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ActivityNotificationContent) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

func (m *ActivityNotificationContent) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ActivityNotificationContent) GetPlatForm() string {
	if m != nil {
		return m.PlatForm
	}
	return ""
}

func (m *ActivityNotificationContent) GetExtParams() string {
	if m != nil {
		return m.ExtParams
	}
	return ""
}

func (m *ActivityNotificationContent) GetActivityId() string {
	if m != nil {
		return m.ActivityId
	}
	return ""
}

func (m *ActivityNotificationContent) GetNotifyType() int32 {
	if m != nil {
		return m.NotifyType
	}
	return 0
}

type OperateNotificationContent struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	PushList             []string `protobuf:"bytes,3,rep,name=push_list,json=pushList,proto3" json:"push_list,omitempty"`
	PlatForm             string   `protobuf:"bytes,4,opt,name=plat_form,json=platForm,proto3" json:"plat_form,omitempty"`
	Batch                int32    `protobuf:"varint,5,opt,name=batch,proto3" json:"batch,omitempty"`
	ExtParams            string   `protobuf:"bytes,6,opt,name=ext_params,json=extParams,proto3" json:"ext_params,omitempty"`
	PushFlag             string   `protobuf:"bytes,7,opt,name=push_flag,json=pushFlag,proto3" json:"push_flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperateNotificationContent) Reset()         { *m = OperateNotificationContent{} }
func (m *OperateNotificationContent) String() string { return proto.CompactTextString(m) }
func (*OperateNotificationContent) ProtoMessage()    {}
func (*OperateNotificationContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{5}
}

func (m *OperateNotificationContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperateNotificationContent.Unmarshal(m, b)
}
func (m *OperateNotificationContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperateNotificationContent.Marshal(b, m, deterministic)
}
func (m *OperateNotificationContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperateNotificationContent.Merge(m, src)
}
func (m *OperateNotificationContent) XXX_Size() int {
	return xxx_messageInfo_OperateNotificationContent.Size(m)
}
func (m *OperateNotificationContent) XXX_DiscardUnknown() {
	xxx_messageInfo_OperateNotificationContent.DiscardUnknown(m)
}

var xxx_messageInfo_OperateNotificationContent proto.InternalMessageInfo

func (m *OperateNotificationContent) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *OperateNotificationContent) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *OperateNotificationContent) GetPushList() []string {
	if m != nil {
		return m.PushList
	}
	return nil
}

func (m *OperateNotificationContent) GetPlatForm() string {
	if m != nil {
		return m.PlatForm
	}
	return ""
}

func (m *OperateNotificationContent) GetBatch() int32 {
	if m != nil {
		return m.Batch
	}
	return 0
}

func (m *OperateNotificationContent) GetExtParams() string {
	if m != nil {
		return m.ExtParams
	}
	return ""
}

func (m *OperateNotificationContent) GetPushFlag() string {
	if m != nil {
		return m.PushFlag
	}
	return ""
}

type NotificationContent struct {
	Id                   int32                           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                          `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content              string                          `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ArticleType          NotificationContent_ArticleType `protobuf:"varint,4,opt,name=article_type,json=articleType,proto3,enum=NotificationContent_ArticleType" json:"article_type,omitempty"`
	ArticleId            string                          `protobuf:"bytes,5,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Behavior             NotificationContent_Behavior    `protobuf:"varint,6,opt,name=behavior,proto3,enum=NotificationContent_Behavior" json:"behavior,omitempty"`
	ToUserId             string                          `protobuf:"bytes,7,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *NotificationContent) Reset()         { *m = NotificationContent{} }
func (m *NotificationContent) String() string { return proto.CompactTextString(m) }
func (*NotificationContent) ProtoMessage()    {}
func (*NotificationContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{6}
}

func (m *NotificationContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationContent.Unmarshal(m, b)
}
func (m *NotificationContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationContent.Marshal(b, m, deterministic)
}
func (m *NotificationContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationContent.Merge(m, src)
}
func (m *NotificationContent) XXX_Size() int {
	return xxx_messageInfo_NotificationContent.Size(m)
}
func (m *NotificationContent) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationContent.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationContent proto.InternalMessageInfo

func (m *NotificationContent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NotificationContent) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *NotificationContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *NotificationContent) GetArticleType() NotificationContent_ArticleType {
	if m != nil {
		return m.ArticleType
	}
	return NotificationContent_NoType
}

func (m *NotificationContent) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

func (m *NotificationContent) GetBehavior() NotificationContent_Behavior {
	if m != nil {
		return m.Behavior
	}
	return NotificationContent_NoBehavior
}

func (m *NotificationContent) GetToUserId() string {
	if m != nil {
		return m.ToUserId
	}
	return ""
}

type SendResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResp) Reset()         { *m = SendResp{} }
func (m *SendResp) String() string { return proto.CompactTextString(m) }
func (*SendResp) ProtoMessage()    {}
func (*SendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{7}
}

func (m *SendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResp.Unmarshal(m, b)
}
func (m *SendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResp.Marshal(b, m, deterministic)
}
func (m *SendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResp.Merge(m, src)
}
func (m *SendResp) XXX_Size() int {
	return xxx_messageInfo_SendResp.Size(m)
}
func (m *SendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendResp proto.InternalMessageInfo

type MsgID struct {
	MsgId                []int64  `protobuf:"varint,8,rep,packed,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgID) Reset()         { *m = MsgID{} }
func (m *MsgID) String() string { return proto.CompactTextString(m) }
func (*MsgID) ProtoMessage()    {}
func (*MsgID) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{8}
}

func (m *MsgID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgID.Unmarshal(m, b)
}
func (m *MsgID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgID.Marshal(b, m, deterministic)
}
func (m *MsgID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgID.Merge(m, src)
}
func (m *MsgID) XXX_Size() int {
	return xxx_messageInfo_MsgID.Size(m)
}
func (m *MsgID) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgID.DiscardUnknown(m)
}

var xxx_messageInfo_MsgID proto.InternalMessageInfo

func (m *MsgID) GetMsgId() []int64 {
	if m != nil {
		return m.MsgId
	}
	return nil
}

type PushResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushResp) Reset()         { *m = PushResp{} }
func (m *PushResp) String() string { return proto.CompactTextString(m) }
func (*PushResp) ProtoMessage()    {}
func (*PushResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{9}
}

func (m *PushResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushResp.Unmarshal(m, b)
}
func (m *PushResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushResp.Marshal(b, m, deterministic)
}
func (m *PushResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushResp.Merge(m, src)
}
func (m *PushResp) XXX_Size() int {
	return xxx_messageInfo_PushResp.Size(m)
}
func (m *PushResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushResp.DiscardUnknown(m)
}

var xxx_messageInfo_PushResp proto.InternalMessageInfo

type PushFlag struct {
	PushFlag             []string `protobuf:"bytes,9,rep,name=push_flag,json=pushFlag,proto3" json:"push_flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushFlag) Reset()         { *m = PushFlag{} }
func (m *PushFlag) String() string { return proto.CompactTextString(m) }
func (*PushFlag) ProtoMessage()    {}
func (*PushFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{10}
}

func (m *PushFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushFlag.Unmarshal(m, b)
}
func (m *PushFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushFlag.Marshal(b, m, deterministic)
}
func (m *PushFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushFlag.Merge(m, src)
}
func (m *PushFlag) XXX_Size() int {
	return xxx_messageInfo_PushFlag.Size(m)
}
func (m *PushFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_PushFlag.DiscardUnknown(m)
}

var xxx_messageInfo_PushFlag proto.InternalMessageInfo

func (m *PushFlag) GetPushFlag() []string {
	if m != nil {
		return m.PushFlag
	}
	return nil
}

type PushStatisticsResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushStatisticsResp) Reset()         { *m = PushStatisticsResp{} }
func (m *PushStatisticsResp) String() string { return proto.CompactTextString(m) }
func (*PushStatisticsResp) ProtoMessage()    {}
func (*PushStatisticsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2b71d662c68aa, []int{11}
}

func (m *PushStatisticsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushStatisticsResp.Unmarshal(m, b)
}
func (m *PushStatisticsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushStatisticsResp.Marshal(b, m, deterministic)
}
func (m *PushStatisticsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushStatisticsResp.Merge(m, src)
}
func (m *PushStatisticsResp) XXX_Size() int {
	return xxx_messageInfo_PushStatisticsResp.Size(m)
}
func (m *PushStatisticsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushStatisticsResp.DiscardUnknown(m)
}

var xxx_messageInfo_PushStatisticsResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("NotificationContent_ArticleType", NotificationContent_ArticleType_name, NotificationContent_ArticleType_value)
	proto.RegisterEnum("NotificationContent_Behavior", NotificationContent_Behavior_name, NotificationContent_Behavior_value)
	proto.RegisterType((*SendPhoneMsgReq)(nil), "SendPhoneMsgReq")
	proto.RegisterType((*SendPhoneMsgResp)(nil), "SendPhoneMsgResp")
	proto.RegisterType((*UserNotification)(nil), "UserNotification")
	proto.RegisterType((*AppNotificationContent)(nil), "AppNotificationContent")
	proto.RegisterType((*ActivityNotificationContent)(nil), "ActivityNotificationContent")
	proto.RegisterType((*OperateNotificationContent)(nil), "OperateNotificationContent")
	proto.RegisterType((*NotificationContent)(nil), "NotificationContent")
	proto.RegisterType((*SendResp)(nil), "SendResp")
	proto.RegisterType((*MsgID)(nil), "MsgID")
	proto.RegisterType((*PushResp)(nil), "PushResp")
	proto.RegisterType((*PushFlag)(nil), "PushFlag")
	proto.RegisterType((*PushStatisticsResp)(nil), "PushStatisticsResp")
}

func init() { proto.RegisterFile("message_push/message_push.proto", fileDescriptor_5ab2b71d662c68aa) }

var fileDescriptor_5ab2b71d662c68aa = []byte{
	// 996 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x6f, 0xe3, 0xc4,
	0x17, 0xdf, 0x24, 0x75, 0x1a, 0xbf, 0xe6, 0x9b, 0x7a, 0x27, 0xf9, 0x6e, 0xad, 0x74, 0xdb, 0xcd,
	0x1a, 0x24, 0x72, 0x32, 0xa8, 0xe5, 0xb2, 0xd2, 0x5e, 0xd2, 0xac, 0x22, 0x22, 0x6d, 0x4b, 0xe5,
	0x36, 0x20, 0x71, 0x89, 0x5c, 0xcf, 0xab, 0x33, 0xaa, 0xed, 0x31, 0xf6, 0xb4, 0x6c, 0x8e, 0x48,
	0xfc, 0x0d, 0x88, 0x23, 0x67, 0xf8, 0x63, 0x90, 0xf8, 0x23, 0x38, 0x73, 0xe6, 0x84, 0x66, 0x6c,
	0x27, 0x76, 0x1a, 0x16, 0x04, 0xb7, 0x79, 0x9f, 0xf7, 0xe6, 0xcd, 0xe7, 0x33, 0xef, 0xcd, 0x0f,
	0x78, 0x11, 0x62, 0x9a, 0xba, 0x3e, 0xce, 0xe3, 0xfb, 0x74, 0xf1, 0x71, 0xd9, 0xb0, 0xe3, 0x84,
	0x0b, 0x6e, 0xcd, 0x60, 0xff, 0x0a, 0x23, 0x7a, 0xb9, 0xe0, 0x11, 0x9e, 0xa7, 0xbe, 0x83, 0x5f,
	0x93, 0x23, 0x80, 0x58, 0x9a, 0xf3, 0x80, 0xa5, 0xc2, 0xac, 0x0d, 0x1a, 0x43, 0xdd, 0xd1, 0x15,
	0xf2, 0x96, 0xa5, 0x82, 0x7c, 0x00, 0xff, 0x13, 0x18, 0xc6, 0x81, 0x2b, 0x70, 0xee, 0x71, 0x8a,
	0x66, 0x7d, 0x50, 0x1b, 0xea, 0x4e, 0xbb, 0x00, 0xc7, 0x9c, 0xa2, 0x45, 0xc0, 0xa8, 0xa6, 0x4d,
	0x63, 0xeb, 0xe7, 0x1a, 0x18, 0xb3, 0x14, 0x93, 0x0b, 0x2e, 0xd8, 0x2d, 0xf3, 0x5c, 0xc1, 0x78,
	0x44, 0x7a, 0xa0, 0x09, 0x26, 0x02, 0x34, 0x6b, 0x2a, 0x4b, 0x66, 0x10, 0x02, 0x3b, 0x37, 0x9c,
	0x2e, 0xf3, 0xd4, 0x6a, 0x4c, 0x0e, 0x41, 0x97, 0xbc, 0x33, 0x56, 0x0d, 0xc5, 0xaa, 0x25, 0x01,
	0x45, 0x4a, 0x3a, 0x03, 0x57, 0xcc, 0x6f, 0x79, 0x12, 0x9a, 0x3b, 0x6a, 0x56, 0x4b, 0x02, 0x13,
	0x9e, 0x84, 0x52, 0x10, 0xbe, 0x13, 0xf3, 0xd8, 0x4d, 0xdc, 0x30, 0x35, 0x35, 0xe5, 0xd5, 0xf1,
	0x9d, 0xb8, 0x54, 0x80, 0xa4, 0x70, 0xe3, 0x0a, 0x6f, 0x61, 0x36, 0x07, 0xb5, 0xa1, 0xe6, 0x64,
	0x86, 0xf5, 0x53, 0x1d, 0x9e, 0x8d, 0xe2, 0xb8, 0x4c, 0x76, 0xcc, 0x23, 0x81, 0x91, 0x20, 0x07,
	0xb0, 0x7b, 0x9f, 0x62, 0x32, 0x67, 0x34, 0x67, 0xdd, 0x94, 0xe6, 0x94, 0x6e, 0xa5, 0xbd, 0x12,
	0xd8, 0x28, 0x0b, 0x3c, 0x02, 0x70, 0x13, 0xc1, 0xbc, 0x00, 0x65, 0x96, 0x8c, 0xb0, 0x9e, 0x23,
	0x53, 0x4a, 0x5e, 0x42, 0xbb, 0x70, 0x8b, 0x65, 0x8c, 0x8a, 0xb3, 0xe6, 0xec, 0xe5, 0xd8, 0xf5,
	0x32, 0x46, 0x99, 0xd7, 0xe3, 0x0f, 0x98, 0x28, 0xd6, 0xba, 0x93, 0x19, 0xd5, 0x7d, 0xd8, 0x55,
	0xb3, 0xd6, 0xfb, 0xf0, 0x12, 0xda, 0x14, 0x1f, 0x98, 0x87, 0x73, 0xc1, 0xef, 0x30, 0x32, 0x5b,
	0x6a, 0xe6, 0x5e, 0x86, 0x5d, 0x4b, 0x48, 0xf2, 0x2a, 0x9a, 0x84, 0x51, 0x53, 0x57, 0x09, 0xf4,
	0x1c, 0x99, 0x52, 0xf2, 0x0c, 0x9a, 0x09, 0xba, 0x29, 0x8f, 0x4c, 0x50, 0xae, 0xdc, 0xb2, 0xbe,
	0xad, 0xc3, 0xe1, 0xc8, 0x13, 0xec, 0x81, 0x89, 0xe5, 0xb6, 0x1d, 0xfb, 0xe7, 0x55, 0xde, 0xe4,
	0xd8, 0x78, 0xcc, 0xb1, 0xb4, 0xfd, 0x3b, 0x95, 0xed, 0xaf, 0x88, 0xd7, 0xde, 0xdb, 0x04, 0xcd,
	0xcd, 0x26, 0x78, 0x01, 0x7b, 0x6e, 0x2e, 0x40, 0x26, 0xde, 0x55, 0x7e, 0x28, 0xa0, 0x29, 0x95,
	0x01, 0x91, 0x54, 0xb6, 0xcc, 0x2a, 0xd2, 0x52, 0xfa, 0x21, 0x83, 0x64, 0x41, 0xac, 0x5f, 0x6b,
	0xd0, 0xff, 0x3c, 0xc6, 0xc4, 0x15, 0xf8, 0xdf, 0xb6, 0xe0, 0xdf, 0x37, 0xfa, 0xaa, 0x93, 0xb5,
	0x52, 0x27, 0xff, 0x9d, 0xf2, 0x62, 0xb9, 0xdb, 0xc0, 0xf5, 0x73, 0xdd, 0x6a, 0xb9, 0x49, 0xe0,
	0xfa, 0xd6, 0x0f, 0x1a, 0x74, 0xb7, 0xa9, 0xe9, 0x40, 0x3d, 0xef, 0x7e, 0xcd, 0xa9, 0x33, 0x5a,
	0xae, 0x49, 0xbd, 0x52, 0x13, 0x13, 0x76, 0xbd, 0x6c, 0x4e, 0x5e, 0xca, 0xc2, 0x24, 0xe3, 0x8d,
	0x1e, 0x97, 0x62, 0x3a, 0x27, 0x03, 0x7b, 0xcb, 0x72, 0xf6, 0x68, 0xdd, 0xf8, 0xd5, 0x53, 0x50,
	0x3d, 0x47, 0xda, 0xe6, 0x39, 0x7a, 0x05, 0xad, 0x1b, 0x5c, 0xb8, 0x0f, 0x8c, 0x67, 0xe7, 0xa4,
	0x73, 0x72, 0xb4, 0x35, 0xff, 0x59, 0x1e, 0xe4, 0xac, 0xc2, 0xc9, 0x73, 0x00, 0xc1, 0xe7, 0x85,
	0xa8, 0x7c, 0x5f, 0x04, 0x9f, 0x29, 0x59, 0xd6, 0x02, 0xf6, 0x4a, 0x9c, 0x08, 0x40, 0xf3, 0x82,
	0xcb, 0x91, 0xf1, 0x84, 0xb4, 0x60, 0xe7, 0x4b, 0x76, 0xc7, 0x0c, 0x20, 0xbb, 0xd0, 0x98, 0xf9,
	0x9e, 0xd1, 0x23, 0xfb, 0xb0, 0x37, 0x8a, 0xbc, 0x05, 0x4f, 0xae, 0x16, 0x6e, 0x82, 0xc6, 0x31,
	0xd1, 0x41, 0xfb, 0x82, 0x51, 0xe4, 0xc6, 0x90, 0x74, 0x00, 0xc6, 0x01, 0xf7, 0xee, 0xa6, 0xa1,
	0xeb, 0xa3, 0xf1, 0x7a, 0x65, 0x67, 0xfe, 0x89, 0xf5, 0x7d, 0x1d, 0x5a, 0x05, 0x3d, 0xe9, 0xbc,
	0xe0, 0x85, 0x65, 0x3c, 0x21, 0x6d, 0xe9, 0x9b, 0xf0, 0x20, 0xe0, 0xdf, 0x18, 0x20, 0xad, 0x99,
	0xef, 0xbd, 0x65, 0x77, 0x48, 0x8d, 0x1e, 0x31, 0xa0, 0x3d, 0xf3, 0xbd, 0x31, 0x0f, 0x02, 0xf4,
	0x04, 0x52, 0xe3, 0x78, 0x85, 0x84, 0x21, 0x46, 0x12, 0x19, 0x12, 0x02, 0x9d, 0xdc, 0x74, 0x30,
	0x0e, 0x18, 0x52, 0xe3, 0x44, 0x46, 0xe5, 0x58, 0x96, 0xe9, 0xb5, 0xa2, 0x7f, 0x4f, 0x99, 0x98,
	0xb8, 0x2c, 0x40, 0x6a, 0x4c, 0x24, 0x8d, 0x33, 0xbc, 0xe6, 0x31, 0xf3, 0x3e, 0xe3, 0xc2, 0xb8,
	0x24, 0x5d, 0xe8, 0x28, 0xba, 0xeb, 0xd4, 0x3f, 0xd6, 0x88, 0x09, 0xdd, 0xb5, 0xb0, 0xb5, 0xe7,
	0xb7, 0x1a, 0xe9, 0xc1, 0xfe, 0xda, 0x93, 0x2d, 0xf2, 0xfb, 0x3a, 0x7e, 0x23, 0xd3, 0x1f, 0xeb,
	0x78, 0xe5, 0xc9, 0xe2, 0xbf, 0xab, 0x5b, 0x00, 0x2d, 0xf9, 0xc4, 0xa8, 0xa7, 0xe5, 0x18, 0xb4,
	0xf3, 0xd4, 0x9f, 0xbe, 0x21, 0xff, 0x87, 0x66, 0x98, 0xfa, 0xb2, 0x62, 0xad, 0x41, 0x63, 0xd8,
	0x70, 0xb4, 0x30, 0xf5, 0xa7, 0x54, 0xc6, 0x5e, 0xde, 0xa7, 0x0b, 0x15, 0xfb, 0x51, 0x36, 0x96,
	0xed, 0x5d, 0xed, 0x7d, 0x7d, 0x7d, 0xd4, 0x54, 0xef, 0xf7, 0x80, 0xc8, 0xc0, 0x2b, 0xe1, 0x0a,
	0x96, 0x0a, 0xe6, 0xa5, 0x72, 0xfa, 0xc9, 0x2f, 0x0d, 0x20, 0xe7, 0xd9, 0x85, 0xa8, 0xbc, 0x98,
	0xc8, 0x9b, 0x89, 0x9c, 0x66, 0x0f, 0x5e, 0xf5, 0x6d, 0xdb, 0xd6, 0x6b, 0x7d, 0xdd, 0x2e, 0x68,
	0x93, 0x0f, 0x61, 0x5f, 0xe6, 0xc8, 0xd3, 0x9d, 0x2d, 0xa7, 0x6f, 0x48, 0xd3, 0x56, 0x42, 0xfa,
	0xba, 0x5d, 0x10, 0x26, 0x9f, 0x40, 0xa7, 0xca, 0x83, 0x64, 0x4e, 0x49, 0xb2, 0xdf, 0xb5, 0x1f,
	0x73, 0x24, 0x23, 0x38, 0x90, 0x6b, 0x6c, 0xb9, 0x8d, 0xc8, 0xa1, 0xfd, 0xd7, 0x77, 0x54, 0x99,
	0xda, 0x18, 0x4c, 0x39, 0xde, 0x76, 0xa9, 0x93, 0xe7, 0xf6, 0x7b, 0xee, 0xfa, 0x72, 0x92, 0x57,
	0xd0, 0x55, 0x49, 0xaa, 0xcf, 0x28, 0x39, 0xb0, 0xb7, 0x3f, 0xac, 0xe5, 0xa9, 0x9f, 0x42, 0x4f,
	0x8e, 0x1f, 0xfd, 0x17, 0x9e, 0xda, 0x9b, 0x50, 0x79, 0xd6, 0x29, 0xb4, 0xcb, 0xdf, 0x0e, 0x62,
	0xd8, 0x1b, 0x9f, 0x9b, 0xfe, 0x53, 0x7b, 0xf3, 0x5f, 0x72, 0x66, 0x7c, 0xd5, 0xb1, 0x2b, 0x5f,
	0xa3, 0x9b, 0xa6, 0xfa, 0x1b, 0x9d, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x2a, 0x9f, 0x62,
	0x3e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessagePushServiceClient is the client API for MessagePushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagePushServiceClient interface {
	SendNotification(ctx context.Context, in *NotificationContent, opts ...grpc.CallOption) (*SendResp, error)
	PushMessageByID(ctx context.Context, in *MsgID, opts ...grpc.CallOption) (*PushResp, error)
	PushStatistics(ctx context.Context, in *PushFlag, opts ...grpc.CallOption) (*PushStatisticsResp, error)
	SendOperateNotification(ctx context.Context, in *OperateNotificationContent, opts ...grpc.CallOption) (*SendResp, error)
	SendActivityNotification(ctx context.Context, in *ActivityNotificationContent, opts ...grpc.CallOption) (*SendResp, error)
	SendAppNotification(ctx context.Context, in *AppNotificationContent, opts ...grpc.CallOption) (*SendResp, error)
	SendUserNotification(ctx context.Context, in *UserNotification, opts ...grpc.CallOption) (*SendResp, error)
	SendPhoneMsg(ctx context.Context, in *SendPhoneMsgReq, opts ...grpc.CallOption) (*SendPhoneMsgResp, error)
}

type messagePushServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessagePushServiceClient(cc *grpc.ClientConn) MessagePushServiceClient {
	return &messagePushServiceClient{cc}
}

func (c *messagePushServiceClient) SendNotification(ctx context.Context, in *NotificationContent, opts ...grpc.CallOption) (*SendResp, error) {
	out := new(SendResp)
	err := c.cc.Invoke(ctx, "/MessagePushService/SendNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagePushServiceClient) PushMessageByID(ctx context.Context, in *MsgID, opts ...grpc.CallOption) (*PushResp, error) {
	out := new(PushResp)
	err := c.cc.Invoke(ctx, "/MessagePushService/PushMessageByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagePushServiceClient) PushStatistics(ctx context.Context, in *PushFlag, opts ...grpc.CallOption) (*PushStatisticsResp, error) {
	out := new(PushStatisticsResp)
	err := c.cc.Invoke(ctx, "/MessagePushService/PushStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagePushServiceClient) SendOperateNotification(ctx context.Context, in *OperateNotificationContent, opts ...grpc.CallOption) (*SendResp, error) {
	out := new(SendResp)
	err := c.cc.Invoke(ctx, "/MessagePushService/SendOperateNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagePushServiceClient) SendActivityNotification(ctx context.Context, in *ActivityNotificationContent, opts ...grpc.CallOption) (*SendResp, error) {
	out := new(SendResp)
	err := c.cc.Invoke(ctx, "/MessagePushService/SendActivityNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagePushServiceClient) SendAppNotification(ctx context.Context, in *AppNotificationContent, opts ...grpc.CallOption) (*SendResp, error) {
	out := new(SendResp)
	err := c.cc.Invoke(ctx, "/MessagePushService/SendAppNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagePushServiceClient) SendUserNotification(ctx context.Context, in *UserNotification, opts ...grpc.CallOption) (*SendResp, error) {
	out := new(SendResp)
	err := c.cc.Invoke(ctx, "/MessagePushService/SendUserNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagePushServiceClient) SendPhoneMsg(ctx context.Context, in *SendPhoneMsgReq, opts ...grpc.CallOption) (*SendPhoneMsgResp, error) {
	out := new(SendPhoneMsgResp)
	err := c.cc.Invoke(ctx, "/MessagePushService/SendPhoneMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagePushServiceServer is the server API for MessagePushService service.
type MessagePushServiceServer interface {
	SendNotification(context.Context, *NotificationContent) (*SendResp, error)
	PushMessageByID(context.Context, *MsgID) (*PushResp, error)
	PushStatistics(context.Context, *PushFlag) (*PushStatisticsResp, error)
	SendOperateNotification(context.Context, *OperateNotificationContent) (*SendResp, error)
	SendActivityNotification(context.Context, *ActivityNotificationContent) (*SendResp, error)
	SendAppNotification(context.Context, *AppNotificationContent) (*SendResp, error)
	SendUserNotification(context.Context, *UserNotification) (*SendResp, error)
	SendPhoneMsg(context.Context, *SendPhoneMsgReq) (*SendPhoneMsgResp, error)
}

// UnimplementedMessagePushServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessagePushServiceServer struct {
}

func (*UnimplementedMessagePushServiceServer) SendNotification(ctx context.Context, req *NotificationContent) (*SendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (*UnimplementedMessagePushServiceServer) PushMessageByID(ctx context.Context, req *MsgID) (*PushResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMessageByID not implemented")
}
func (*UnimplementedMessagePushServiceServer) PushStatistics(ctx context.Context, req *PushFlag) (*PushStatisticsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushStatistics not implemented")
}
func (*UnimplementedMessagePushServiceServer) SendOperateNotification(ctx context.Context, req *OperateNotificationContent) (*SendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOperateNotification not implemented")
}
func (*UnimplementedMessagePushServiceServer) SendActivityNotification(ctx context.Context, req *ActivityNotificationContent) (*SendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendActivityNotification not implemented")
}
func (*UnimplementedMessagePushServiceServer) SendAppNotification(ctx context.Context, req *AppNotificationContent) (*SendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAppNotification not implemented")
}
func (*UnimplementedMessagePushServiceServer) SendUserNotification(ctx context.Context, req *UserNotification) (*SendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendUserNotification not implemented")
}
func (*UnimplementedMessagePushServiceServer) SendPhoneMsg(ctx context.Context, req *SendPhoneMsgReq) (*SendPhoneMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPhoneMsg not implemented")
}

func RegisterMessagePushServiceServer(s *grpc.Server, srv MessagePushServiceServer) {
	s.RegisterService(&_MessagePushService_serviceDesc, srv)
}

func _MessagePushService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagePushServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessagePushService/SendNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagePushServiceServer).SendNotification(ctx, req.(*NotificationContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagePushService_PushMessageByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagePushServiceServer).PushMessageByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessagePushService/PushMessageByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagePushServiceServer).PushMessageByID(ctx, req.(*MsgID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagePushService_PushStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushFlag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagePushServiceServer).PushStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessagePushService/PushStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagePushServiceServer).PushStatistics(ctx, req.(*PushFlag))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagePushService_SendOperateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateNotificationContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagePushServiceServer).SendOperateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessagePushService/SendOperateNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagePushServiceServer).SendOperateNotification(ctx, req.(*OperateNotificationContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagePushService_SendActivityNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityNotificationContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagePushServiceServer).SendActivityNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessagePushService/SendActivityNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagePushServiceServer).SendActivityNotification(ctx, req.(*ActivityNotificationContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagePushService_SendAppNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppNotificationContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagePushServiceServer).SendAppNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessagePushService/SendAppNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagePushServiceServer).SendAppNotification(ctx, req.(*AppNotificationContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagePushService_SendUserNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagePushServiceServer).SendUserNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessagePushService/SendUserNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagePushServiceServer).SendUserNotification(ctx, req.(*UserNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessagePushService_SendPhoneMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPhoneMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagePushServiceServer).SendPhoneMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessagePushService/SendPhoneMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagePushServiceServer).SendPhoneMsg(ctx, req.(*SendPhoneMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessagePushService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MessagePushService",
	HandlerType: (*MessagePushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotification",
			Handler:    _MessagePushService_SendNotification_Handler,
		},
		{
			MethodName: "PushMessageByID",
			Handler:    _MessagePushService_PushMessageByID_Handler,
		},
		{
			MethodName: "PushStatistics",
			Handler:    _MessagePushService_PushStatistics_Handler,
		},
		{
			MethodName: "SendOperateNotification",
			Handler:    _MessagePushService_SendOperateNotification_Handler,
		},
		{
			MethodName: "SendActivityNotification",
			Handler:    _MessagePushService_SendActivityNotification_Handler,
		},
		{
			MethodName: "SendAppNotification",
			Handler:    _MessagePushService_SendAppNotification_Handler,
		},
		{
			MethodName: "SendUserNotification",
			Handler:    _MessagePushService_SendUserNotification_Handler,
		},
		{
			MethodName: "SendPhoneMsg",
			Handler:    _MessagePushService_SendPhoneMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message_push/message_push.proto",
}
