// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: im/im.proto

package im

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SendGroupMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LiveRoomId string `protobuf:"bytes,1,opt,name=live_room_id,json=liveRoomId,proto3" json:"live_room_id,omitempty"`
	UserName   string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserId     string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content    string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SendGroupMsgReq) Reset() {
	*x = SendGroupMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGroupMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMsgReq) ProtoMessage() {}

func (x *SendGroupMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMsgReq.ProtoReflect.Descriptor instead.
func (*SendGroupMsgReq) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{0}
}

func (x *SendGroupMsgReq) GetLiveRoomId() string {
	if x != nil {
		return x.LiveRoomId
	}
	return ""
}

func (x *SendGroupMsgReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SendGroupMsgReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendGroupMsgReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendGroupMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendGroupMsgResp) Reset() {
	*x = SendGroupMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGroupMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMsgResp) ProtoMessage() {}

func (x *SendGroupMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMsgResp.ProtoReflect.Descriptor instead.
func (*SendGroupMsgResp) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{1}
}

type AccountImportReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FaceUrl  string `protobuf:"bytes,3,opt,name=face_url,json=faceUrl,proto3" json:"face_url,omitempty"`
}

func (x *AccountImportReq) Reset() {
	*x = AccountImportReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountImportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountImportReq) ProtoMessage() {}

func (x *AccountImportReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountImportReq.ProtoReflect.Descriptor instead.
func (*AccountImportReq) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{2}
}

func (x *AccountImportReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountImportReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AccountImportReq) GetFaceUrl() string {
	if x != nil {
		return x.FaceUrl
	}
	return ""
}

type AccountImportResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccountImportResp) Reset() {
	*x = AccountImportResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountImportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountImportResp) ProtoMessage() {}

func (x *AccountImportResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountImportResp.ProtoReflect.Descriptor instead.
func (*AccountImportResp) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{3}
}

type AddRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerUserId string `protobuf:"bytes,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	RoomId      int64  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomName    string `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
}

func (x *AddRoomReq) Reset() {
	*x = AddRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomReq) ProtoMessage() {}

func (x *AddRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomReq.ProtoReflect.Descriptor instead.
func (*AddRoomReq) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{4}
}

func (x *AddRoomReq) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *AddRoomReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *AddRoomReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type AddRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddRoomResp) Reset() {
	*x = AddRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomResp) ProtoMessage() {}

func (x *AddRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomResp.ProtoReflect.Descriptor instead.
func (*AddRoomResp) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{5}
}

type DestroyGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *DestroyGroupReq) Reset() {
	*x = DestroyGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyGroupReq) ProtoMessage() {}

func (x *DestroyGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyGroupReq.ProtoReflect.Descriptor instead.
func (*DestroyGroupReq) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{6}
}

func (x *DestroyGroupReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type DestroyGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DestroyGroupResp) Reset() {
	*x = DestroyGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyGroupResp) ProtoMessage() {}

func (x *DestroyGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyGroupResp.ProtoReflect.Descriptor instead.
func (*DestroyGroupResp) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{7}
}

type GetGroupInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId []int64 `protobuf:"varint,1,rep,packed,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *GetGroupInfoReq) Reset() {
	*x = GetGroupInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoReq) ProtoMessage() {}

func (x *GetGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoReq.ProtoReflect.Descriptor instead.
func (*GetGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{8}
}

func (x *GetGroupInfoReq) GetRoomId() []int64 {
	if x != nil {
		return x.RoomId
	}
	return nil
}

type GetGroupInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupInfo []*GroupInfo `protobuf:"bytes,1,rep,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
}

func (x *GetGroupInfoResp) Reset() {
	*x = GetGroupInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoResp) ProtoMessage() {}

func (x *GetGroupInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoResp.ProtoReflect.Descriptor instead.
func (*GetGroupInfoResp) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{9}
}

func (x *GetGroupInfoResp) GetGroupInfo() []*GroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

type GroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MemberNum int32 `protobuf:"varint,2,opt,name=member_num,json=memberNum,proto3" json:"member_num,omitempty"`
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{10}
}

func (x *GroupInfo) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GroupInfo) GetMemberNum() int32 {
	if x != nil {
		return x.MemberNum
	}
	return 0
}

type MakeGenSigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *MakeGenSigReq) Reset() {
	*x = MakeGenSigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeGenSigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeGenSigReq) ProtoMessage() {}

func (x *MakeGenSigReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeGenSigReq.ProtoReflect.Descriptor instead.
func (*MakeGenSigReq) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{11}
}

func (x *MakeGenSigReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MakeGenSigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig string `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *MakeGenSigResp) Reset() {
	*x = MakeGenSigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeGenSigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeGenSigResp) ProtoMessage() {}

func (x *MakeGenSigResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeGenSigResp.ProtoReflect.Descriptor instead.
func (*MakeGenSigResp) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{12}
}

func (x *MakeGenSigResp) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

type MakeAdminGenSigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MakeAdminGenSigReq) Reset() {
	*x = MakeAdminGenSigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeAdminGenSigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAdminGenSigReq) ProtoMessage() {}

func (x *MakeAdminGenSigReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAdminGenSigReq.ProtoReflect.Descriptor instead.
func (*MakeAdminGenSigReq) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{13}
}

type MakeAdminGenSigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig string `protobuf:"bytes,1,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (x *MakeAdminGenSigResp) Reset() {
	*x = MakeAdminGenSigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_im_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeAdminGenSigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAdminGenSigResp) ProtoMessage() {}

func (x *MakeAdminGenSigResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_im_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAdminGenSigResp.ProtoReflect.Descriptor instead.
func (*MakeAdminGenSigResp) Descriptor() ([]byte, []int) {
	return file_im_im_proto_rawDescGZIP(), []int{14}
}

func (x *MakeAdminGenSigResp) GetSig() string {
	if x != nil {
		return x.Sig
	}
	return ""
}

var File_im_im_proto protoreflect.FileDescriptor

var file_im_im_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x6d, 0x2f, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01,
	0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x63, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x13, 0x0a, 0x11,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x66, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x22, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x41, 0x64, 0x64,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2a, 0x0a, 0x0f, 0x44, 0x65, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x43, 0x0a, 0x09, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x28, 0x0a, 0x0d, 0x4d, 0x61, 0x6b, 0x65,
	0x47, 0x65, 0x6e, 0x53, 0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x22, 0x0a, 0x0e, 0x4d, 0x61, 0x6b, 0x65, 0x47, 0x65, 0x6e, 0x53, 0x69, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x69, 0x67, 0x22, 0x14, 0x0a, 0x12, 0x4d, 0x61, 0x6b, 0x65, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x47, 0x65, 0x6e, 0x53, 0x69, 0x67, 0x52, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x13,
	0x4d, 0x61, 0x6b, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65, 0x6e, 0x53, 0x69, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x69, 0x67, 0x32, 0xf5, 0x02, 0x0a, 0x09, 0x49, 0x4d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x11, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0b, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x33, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x10, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x0a, 0x4d,
	0x61, 0x6b, 0x65, 0x47, 0x65, 0x6e, 0x53, 0x69, 0x67, 0x12, 0x0e, 0x2e, 0x4d, 0x61, 0x6b, 0x65,
	0x47, 0x65, 0x6e, 0x53, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x4d, 0x61, 0x6b, 0x65,
	0x47, 0x65, 0x6e, 0x53, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0f, 0x4d, 0x61,
	0x6b, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65, 0x6e, 0x53, 0x69, 0x67, 0x12, 0x13, 0x2e,
	0x4d, 0x61, 0x6b, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65, 0x6e, 0x53, 0x69, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65,
	0x6e, 0x53, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_im_im_proto_rawDescOnce sync.Once
	file_im_im_proto_rawDescData = file_im_im_proto_rawDesc
)

func file_im_im_proto_rawDescGZIP() []byte {
	file_im_im_proto_rawDescOnce.Do(func() {
		file_im_im_proto_rawDescData = protoimpl.X.CompressGZIP(file_im_im_proto_rawDescData)
	})
	return file_im_im_proto_rawDescData
}

var file_im_im_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_im_im_proto_goTypes = []interface{}{
	(*SendGroupMsgReq)(nil),     // 0: SendGroupMsgReq
	(*SendGroupMsgResp)(nil),    // 1: SendGroupMsgResp
	(*AccountImportReq)(nil),    // 2: AccountImportReq
	(*AccountImportResp)(nil),   // 3: AccountImportResp
	(*AddRoomReq)(nil),          // 4: AddRoomReq
	(*AddRoomResp)(nil),         // 5: AddRoomResp
	(*DestroyGroupReq)(nil),     // 6: DestroyGroupReq
	(*DestroyGroupResp)(nil),    // 7: DestroyGroupResp
	(*GetGroupInfoReq)(nil),     // 8: GetGroupInfoReq
	(*GetGroupInfoResp)(nil),    // 9: GetGroupInfoResp
	(*GroupInfo)(nil),           // 10: GroupInfo
	(*MakeGenSigReq)(nil),       // 11: MakeGenSigReq
	(*MakeGenSigResp)(nil),      // 12: MakeGenSigResp
	(*MakeAdminGenSigReq)(nil),  // 13: MakeAdminGenSigReq
	(*MakeAdminGenSigResp)(nil), // 14: MakeAdminGenSigResp
}
var file_im_im_proto_depIdxs = []int32{
	10, // 0: GetGroupInfoResp.group_info:type_name -> GroupInfo
	2,  // 1: IMService.AccountImport:input_type -> AccountImportReq
	4,  // 2: IMService.AddRoom:input_type -> AddRoomReq
	6,  // 3: IMService.DestroyGroup:input_type -> DestroyGroupReq
	8,  // 4: IMService.GetGroupInfo:input_type -> GetGroupInfoReq
	11, // 5: IMService.MakeGenSig:input_type -> MakeGenSigReq
	13, // 6: IMService.MakeAdminGenSig:input_type -> MakeAdminGenSigReq
	0,  // 7: IMService.SendGroupMsg:input_type -> SendGroupMsgReq
	3,  // 8: IMService.AccountImport:output_type -> AccountImportResp
	5,  // 9: IMService.AddRoom:output_type -> AddRoomResp
	7,  // 10: IMService.DestroyGroup:output_type -> DestroyGroupResp
	9,  // 11: IMService.GetGroupInfo:output_type -> GetGroupInfoResp
	12, // 12: IMService.MakeGenSig:output_type -> MakeGenSigResp
	14, // 13: IMService.MakeAdminGenSig:output_type -> MakeAdminGenSigResp
	1,  // 14: IMService.SendGroupMsg:output_type -> SendGroupMsgResp
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_im_im_proto_init() }
func file_im_im_proto_init() {
	if File_im_im_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_im_im_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGroupMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGroupMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountImportReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountImportResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeGenSigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeGenSigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeAdminGenSigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_im_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeAdminGenSigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_im_im_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_im_proto_goTypes,
		DependencyIndexes: file_im_im_proto_depIdxs,
		MessageInfos:      file_im_im_proto_msgTypes,
	}.Build()
	File_im_im_proto = out.File
	file_im_im_proto_rawDesc = nil
	file_im_im_proto_goTypes = nil
	file_im_im_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IMServiceClient is the client API for IMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IMServiceClient interface {
	// 导入账号
	AccountImport(ctx context.Context, in *AccountImportReq, opts ...grpc.CallOption) (*AccountImportResp, error)
	// 添加直播间
	AddRoom(ctx context.Context, in *AddRoomReq, opts ...grpc.CallOption) (*AddRoomResp, error)
	// 删除直播间
	DestroyGroup(ctx context.Context, in *DestroyGroupReq, opts ...grpc.CallOption) (*DestroyGroupResp, error)
	// 获取直播间信息
	GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
	// 给用户签名
	MakeGenSig(ctx context.Context, in *MakeGenSigReq, opts ...grpc.CallOption) (*MakeGenSigResp, error)
	//  管理员签名
	MakeAdminGenSig(ctx context.Context, in *MakeAdminGenSigReq, opts ...grpc.CallOption) (*MakeAdminGenSigResp, error)
	SendGroupMsg(ctx context.Context, in *SendGroupMsgReq, opts ...grpc.CallOption) (*SendGroupMsgResp, error)
}

type iMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIMServiceClient(cc grpc.ClientConnInterface) IMServiceClient {
	return &iMServiceClient{cc}
}

func (c *iMServiceClient) AccountImport(ctx context.Context, in *AccountImportReq, opts ...grpc.CallOption) (*AccountImportResp, error) {
	out := new(AccountImportResp)
	err := c.cc.Invoke(ctx, "/IMService/AccountImport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMServiceClient) AddRoom(ctx context.Context, in *AddRoomReq, opts ...grpc.CallOption) (*AddRoomResp, error) {
	out := new(AddRoomResp)
	err := c.cc.Invoke(ctx, "/IMService/AddRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMServiceClient) DestroyGroup(ctx context.Context, in *DestroyGroupReq, opts ...grpc.CallOption) (*DestroyGroupResp, error) {
	out := new(DestroyGroupResp)
	err := c.cc.Invoke(ctx, "/IMService/DestroyGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMServiceClient) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	out := new(GetGroupInfoResp)
	err := c.cc.Invoke(ctx, "/IMService/GetGroupInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMServiceClient) MakeGenSig(ctx context.Context, in *MakeGenSigReq, opts ...grpc.CallOption) (*MakeGenSigResp, error) {
	out := new(MakeGenSigResp)
	err := c.cc.Invoke(ctx, "/IMService/MakeGenSig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMServiceClient) MakeAdminGenSig(ctx context.Context, in *MakeAdminGenSigReq, opts ...grpc.CallOption) (*MakeAdminGenSigResp, error) {
	out := new(MakeAdminGenSigResp)
	err := c.cc.Invoke(ctx, "/IMService/MakeAdminGenSig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMServiceClient) SendGroupMsg(ctx context.Context, in *SendGroupMsgReq, opts ...grpc.CallOption) (*SendGroupMsgResp, error) {
	out := new(SendGroupMsgResp)
	err := c.cc.Invoke(ctx, "/IMService/SendGroupMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMServiceServer is the server API for IMService service.
type IMServiceServer interface {
	// 导入账号
	AccountImport(context.Context, *AccountImportReq) (*AccountImportResp, error)
	// 添加直播间
	AddRoom(context.Context, *AddRoomReq) (*AddRoomResp, error)
	// 删除直播间
	DestroyGroup(context.Context, *DestroyGroupReq) (*DestroyGroupResp, error)
	// 获取直播间信息
	GetGroupInfo(context.Context, *GetGroupInfoReq) (*GetGroupInfoResp, error)
	// 给用户签名
	MakeGenSig(context.Context, *MakeGenSigReq) (*MakeGenSigResp, error)
	//  管理员签名
	MakeAdminGenSig(context.Context, *MakeAdminGenSigReq) (*MakeAdminGenSigResp, error)
	SendGroupMsg(context.Context, *SendGroupMsgReq) (*SendGroupMsgResp, error)
}

// UnimplementedIMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIMServiceServer struct {
}

func (*UnimplementedIMServiceServer) AccountImport(context.Context, *AccountImportReq) (*AccountImportResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountImport not implemented")
}
func (*UnimplementedIMServiceServer) AddRoom(context.Context, *AddRoomReq) (*AddRoomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRoom not implemented")
}
func (*UnimplementedIMServiceServer) DestroyGroup(context.Context, *DestroyGroupReq) (*DestroyGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyGroup not implemented")
}
func (*UnimplementedIMServiceServer) GetGroupInfo(context.Context, *GetGroupInfoReq) (*GetGroupInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupInfo not implemented")
}
func (*UnimplementedIMServiceServer) MakeGenSig(context.Context, *MakeGenSigReq) (*MakeGenSigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeGenSig not implemented")
}
func (*UnimplementedIMServiceServer) MakeAdminGenSig(context.Context, *MakeAdminGenSigReq) (*MakeAdminGenSigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeAdminGenSig not implemented")
}
func (*UnimplementedIMServiceServer) SendGroupMsg(context.Context, *SendGroupMsgReq) (*SendGroupMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGroupMsg not implemented")
}

func RegisterIMServiceServer(s *grpc.Server, srv IMServiceServer) {
	s.RegisterService(&_IMService_serviceDesc, srv)
}

func _IMService_AccountImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountImportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServiceServer).AccountImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IMService/AccountImport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServiceServer).AccountImport(ctx, req.(*AccountImportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMService_AddRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServiceServer).AddRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IMService/AddRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServiceServer).AddRoom(ctx, req.(*AddRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMService_DestroyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServiceServer).DestroyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IMService/DestroyGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServiceServer).DestroyGroup(ctx, req.(*DestroyGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMService_GetGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServiceServer).GetGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IMService/GetGroupInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServiceServer).GetGroupInfo(ctx, req.(*GetGroupInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMService_MakeGenSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeGenSigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServiceServer).MakeGenSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IMService/MakeGenSig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServiceServer).MakeGenSig(ctx, req.(*MakeGenSigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMService_MakeAdminGenSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeAdminGenSigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServiceServer).MakeAdminGenSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IMService/MakeAdminGenSig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServiceServer).MakeAdminGenSig(ctx, req.(*MakeAdminGenSigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMService_SendGroupMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMServiceServer).SendGroupMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IMService/SendGroupMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMServiceServer).SendGroupMsg(ctx, req.(*SendGroupMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "IMService",
	HandlerType: (*IMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountImport",
			Handler:    _IMService_AccountImport_Handler,
		},
		{
			MethodName: "AddRoom",
			Handler:    _IMService_AddRoom_Handler,
		},
		{
			MethodName: "DestroyGroup",
			Handler:    _IMService_DestroyGroup_Handler,
		},
		{
			MethodName: "GetGroupInfo",
			Handler:    _IMService_GetGroupInfo_Handler,
		},
		{
			MethodName: "MakeGenSig",
			Handler:    _IMService_MakeGenSig_Handler,
		},
		{
			MethodName: "MakeAdminGenSig",
			Handler:    _IMService_MakeAdminGenSig_Handler,
		},
		{
			MethodName: "SendGroupMsg",
			Handler:    _IMService_SendGroupMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im/im.proto",
}
