// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: recommend/recommend.proto

package recommend

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 行为枚举值
type BehaviorType int32

const (
	BehaviorType_view    BehaviorType = 0 // 浏览
	BehaviorType_share   BehaviorType = 1 // 分享
	BehaviorType_collect BehaviorType = 2 // 收藏
	BehaviorType_like    BehaviorType = 3 // 点赞
	BehaviorType_comment BehaviorType = 4 // 评论
)

// Enum value maps for BehaviorType.
var (
	BehaviorType_name = map[int32]string{
		0: "view",
		1: "share",
		2: "collect",
		3: "like",
		4: "comment",
	}
	BehaviorType_value = map[string]int32{
		"view":    0,
		"share":   1,
		"collect": 2,
		"like":    3,
		"comment": 4,
	}
)

func (x BehaviorType) Enum() *BehaviorType {
	p := new(BehaviorType)
	*p = x
	return p
}

func (x BehaviorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BehaviorType) Descriptor() protoreflect.EnumDescriptor {
	return file_recommend_recommend_proto_enumTypes[0].Descriptor()
}

func (BehaviorType) Type() protoreflect.EnumType {
	return &file_recommend_recommend_proto_enumTypes[0]
}

func (x BehaviorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BehaviorType.Descriptor instead.
func (BehaviorType) EnumDescriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{0}
}

type CollectUserBehaviorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId      int64        `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	LiveRoomId   int64        `protobuf:"varint,3,opt,name=live_room_id,json=liveRoomId,proto3" json:"live_room_id,omitempty"`
	BehaviorType BehaviorType `protobuf:"varint,4,opt,name=behavior_type,json=behaviorType,proto3,enum=BehaviorType" json:"behavior_type,omitempty"`
}

func (x *CollectUserBehaviorReq) Reset() {
	*x = CollectUserBehaviorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectUserBehaviorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectUserBehaviorReq) ProtoMessage() {}

func (x *CollectUserBehaviorReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectUserBehaviorReq.ProtoReflect.Descriptor instead.
func (*CollectUserBehaviorReq) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{0}
}

func (x *CollectUserBehaviorReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectUserBehaviorReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CollectUserBehaviorReq) GetLiveRoomId() int64 {
	if x != nil {
		return x.LiveRoomId
	}
	return 0
}

func (x *CollectUserBehaviorReq) GetBehaviorType() BehaviorType {
	if x != nil {
		return x.BehaviorType
	}
	return BehaviorType_view
}

type CollectUserBehaviorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollectUserBehaviorResp) Reset() {
	*x = CollectUserBehaviorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectUserBehaviorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectUserBehaviorResp) ProtoMessage() {}

func (x *CollectUserBehaviorResp) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectUserBehaviorResp.ProtoReflect.Descriptor instead.
func (*CollectUserBehaviorResp) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{1}
}

type CollectUserHistoryTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TagId  int64 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
}

func (x *CollectUserHistoryTagReq) Reset() {
	*x = CollectUserHistoryTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectUserHistoryTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectUserHistoryTagReq) ProtoMessage() {}

func (x *CollectUserHistoryTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectUserHistoryTagReq.ProtoReflect.Descriptor instead.
func (*CollectUserHistoryTagReq) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{2}
}

func (x *CollectUserHistoryTagReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CollectUserHistoryTagReq) GetTagId() int64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

type CollectUserHistoryTagResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollectUserHistoryTagResp) Reset() {
	*x = CollectUserHistoryTagResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectUserHistoryTagResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectUserHistoryTagResp) ProtoMessage() {}

func (x *CollectUserHistoryTagResp) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectUserHistoryTagResp.ProtoReflect.Descriptor instead.
func (*CollectUserHistoryTagResp) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{3}
}

type GetRecommendListByUserIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page   int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetRecommendListByUserIDReq) Reset() {
	*x = GetRecommendListByUserIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecommendListByUserIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendListByUserIDReq) ProtoMessage() {}

func (x *GetRecommendListByUserIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendListByUserIDReq.ProtoReflect.Descriptor instead.
func (*GetRecommendListByUserIDReq) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendListByUserIDReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRecommendListByUserIDReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetRecommendListByUserIDResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecommendVideo []int64 `protobuf:"varint,1,rep,packed,name=recommend_video,json=recommendVideo,proto3" json:"recommend_video,omitempty"`
	RecommendLive  []int64 `protobuf:"varint,2,rep,packed,name=recommend_live,json=recommendLive,proto3" json:"recommend_live,omitempty"`
}

func (x *GetRecommendListByUserIDResp) Reset() {
	*x = GetRecommendListByUserIDResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecommendListByUserIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendListByUserIDResp) ProtoMessage() {}

func (x *GetRecommendListByUserIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendListByUserIDResp.ProtoReflect.Descriptor instead.
func (*GetRecommendListByUserIDResp) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecommendListByUserIDResp) GetRecommendVideo() []int64 {
	if x != nil {
		return x.RecommendVideo
	}
	return nil
}

func (x *GetRecommendListByUserIDResp) GetRecommendLive() []int64 {
	if x != nil {
		return x.RecommendLive
	}
	return nil
}

type GetLivesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page   int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetLivesReq) Reset() {
	*x = GetLivesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLivesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLivesReq) ProtoMessage() {}

func (x *GetLivesReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLivesReq.ProtoReflect.Descriptor instead.
func (*GetLivesReq) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{6}
}

func (x *GetLivesReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetLivesReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetLivesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []int64 `protobuf:"varint,2,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *GetLivesResp) Reset() {
	*x = GetLivesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLivesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLivesResp) ProtoMessage() {}

func (x *GetLivesResp) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLivesResp.ProtoReflect.Descriptor instead.
func (*GetLivesResp) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{7}
}

func (x *GetLivesResp) GetList() []int64 {
	if x != nil {
		return x.List
	}
	return nil
}

type GetVideosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page   int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetVideosReq) Reset() {
	*x = GetVideosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosReq) ProtoMessage() {}

func (x *GetVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosReq.ProtoReflect.Descriptor instead.
func (*GetVideosReq) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{8}
}

func (x *GetVideosReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetVideosReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetVideosResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []int64 `protobuf:"varint,2,rep,packed,name=list,proto3" json:"list,omitempty"`
}

func (x *GetVideosResp) Reset() {
	*x = GetVideosResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosResp) ProtoMessage() {}

func (x *GetVideosResp) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosResp.ProtoReflect.Descriptor instead.
func (*GetVideosResp) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{9}
}

func (x *GetVideosResp) GetList() []int64 {
	if x != nil {
		return x.List
	}
	return nil
}

type SyncLiveStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanRecommendLiveId    []int64 `protobuf:"varint,1,rep,packed,name=can_recommend_live_id,json=canRecommendLiveId,proto3" json:"can_recommend_live_id,omitempty"`
	CannotRecommendLiveId []int64 `protobuf:"varint,2,rep,packed,name=cannot_recommend_live_id,json=cannotRecommendLiveId,proto3" json:"cannot_recommend_live_id,omitempty"`
}

func (x *SyncLiveStateReq) Reset() {
	*x = SyncLiveStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncLiveStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLiveStateReq) ProtoMessage() {}

func (x *SyncLiveStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLiveStateReq.ProtoReflect.Descriptor instead.
func (*SyncLiveStateReq) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{10}
}

func (x *SyncLiveStateReq) GetCanRecommendLiveId() []int64 {
	if x != nil {
		return x.CanRecommendLiveId
	}
	return nil
}

func (x *SyncLiveStateReq) GetCannotRecommendLiveId() []int64 {
	if x != nil {
		return x.CannotRecommendLiveId
	}
	return nil
}

type SyncLiveStateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncLiveStateResp) Reset() {
	*x = SyncLiveStateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncLiveStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncLiveStateResp) ProtoMessage() {}

func (x *SyncLiveStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncLiveStateResp.ProtoReflect.Descriptor instead.
func (*SyncLiveStateResp) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{11}
}

type SyncVideoStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanRecommendVideoId    []*CanRecommendVideo `protobuf:"bytes,1,rep,name=can_recommend_video_id,json=canRecommendVideoId,proto3" json:"can_recommend_video_id,omitempty"`
	CannotRecommendVideoId []int64              `protobuf:"varint,2,rep,packed,name=cannot_recommend_video_id,json=cannotRecommendVideoId,proto3" json:"cannot_recommend_video_id,omitempty"`
}

func (x *SyncVideoStateReq) Reset() {
	*x = SyncVideoStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncVideoStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncVideoStateReq) ProtoMessage() {}

func (x *SyncVideoStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncVideoStateReq.ProtoReflect.Descriptor instead.
func (*SyncVideoStateReq) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{12}
}

func (x *SyncVideoStateReq) GetCanRecommendVideoId() []*CanRecommendVideo {
	if x != nil {
		return x.CanRecommendVideoId
	}
	return nil
}

func (x *SyncVideoStateReq) GetCannotRecommendVideoId() []int64 {
	if x != nil {
		return x.CannotRecommendVideoId
	}
	return nil
}

type CanRecommendVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId    int64   `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	TagIds     []int64 `protobuf:"varint,2,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	UpdateTime int64   `protobuf:"varint,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *CanRecommendVideo) Reset() {
	*x = CanRecommendVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanRecommendVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanRecommendVideo) ProtoMessage() {}

func (x *CanRecommendVideo) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanRecommendVideo.ProtoReflect.Descriptor instead.
func (*CanRecommendVideo) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{13}
}

func (x *CanRecommendVideo) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CanRecommendVideo) GetTagIds() []int64 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *CanRecommendVideo) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type SyncVideoStateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncVideoStateResp) Reset() {
	*x = SyncVideoStateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncVideoStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncVideoStateResp) ProtoMessage() {}

func (x *SyncVideoStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncVideoStateResp.ProtoReflect.Descriptor instead.
func (*SyncVideoStateResp) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{14}
}

type DeleteVideoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId int64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
}

func (x *DeleteVideoReq) Reset() {
	*x = DeleteVideoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoReq) ProtoMessage() {}

func (x *DeleteVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoReq.ProtoReflect.Descriptor instead.
func (*DeleteVideoReq) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteVideoReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type DeleteVideoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteVideoResp) Reset() {
	*x = DeleteVideoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_recommend_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResp) ProtoMessage() {}

func (x *DeleteVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_recommend_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResp.ProtoReflect.Descriptor instead.
func (*DeleteVideoResp) Descriptor() ([]byte, []int) {
	return file_recommend_recommend_proto_rawDescGZIP(), []int{16}
}

var File_recommend_recommend_proto protoreflect.FileDescriptor

var file_recommend_recommend_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x2f, 0x72, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x16,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x69,
	0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x0d,
	0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0c, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x19, 0x0a, 0x17, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4a, 0x0a, 0x18, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x4a, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x22, 0x6e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x5f, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x76, 0x65,
	0x22, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x22, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0x3b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x23, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x7e, 0x0a, 0x10, 0x53, 0x79, 0x6e, 0x63, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x15, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x12, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x18, 0x63, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x69,
	0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x15, 0x63, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x76, 0x65,
	0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x79, 0x6e, 0x63, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x97, 0x01, 0x0a, 0x11, 0x53, 0x79, 0x6e, 0x63,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x47, 0x0a,
	0x16, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x5f, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x43, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x52, 0x13, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x19, 0x63, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x16, 0x63, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x22, 0x68, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x06, 0x74, 0x61, 0x67, 0x49, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x53,
	0x79, 0x6e, 0x63, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x2b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x22, 0x11,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x2a, 0x47, 0x0a, 0x0c, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x10, 0x03, 0x12, 0x0b, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x04, 0x32, 0xff, 0x03, 0x0a, 0x10, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x48, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x17, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x15, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x54,
	0x61, 0x67, 0x12, 0x19, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x57, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x27, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x73, 0x12, 0x0c,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x12, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0d, 0x53, 0x79, 0x6e, 0x63, 0x4c,
	0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x4c,
	0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x53, 0x79,
	0x6e, 0x63, 0x4c, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x39, 0x0a, 0x0e, 0x53, 0x79, 0x6e, 0x63, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x12, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0b, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x0f, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0d, 0x5a, 0x0b,
	0x2e, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_recommend_recommend_proto_rawDescOnce sync.Once
	file_recommend_recommend_proto_rawDescData = file_recommend_recommend_proto_rawDesc
)

func file_recommend_recommend_proto_rawDescGZIP() []byte {
	file_recommend_recommend_proto_rawDescOnce.Do(func() {
		file_recommend_recommend_proto_rawDescData = protoimpl.X.CompressGZIP(file_recommend_recommend_proto_rawDescData)
	})
	return file_recommend_recommend_proto_rawDescData
}

var file_recommend_recommend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recommend_recommend_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_recommend_recommend_proto_goTypes = []interface{}{
	(BehaviorType)(0),                    // 0: BehaviorType
	(*CollectUserBehaviorReq)(nil),       // 1: CollectUserBehaviorReq
	(*CollectUserBehaviorResp)(nil),      // 2: CollectUserBehaviorResp
	(*CollectUserHistoryTagReq)(nil),     // 3: CollectUserHistoryTagReq
	(*CollectUserHistoryTagResp)(nil),    // 4: CollectUserHistoryTagResp
	(*GetRecommendListByUserIDReq)(nil),  // 5: GetRecommendListByUserIDReq
	(*GetRecommendListByUserIDResp)(nil), // 6: GetRecommendListByUserIDResp
	(*GetLivesReq)(nil),                  // 7: GetLivesReq
	(*GetLivesResp)(nil),                 // 8: GetLivesResp
	(*GetVideosReq)(nil),                 // 9: GetVideosReq
	(*GetVideosResp)(nil),                // 10: GetVideosResp
	(*SyncLiveStateReq)(nil),             // 11: SyncLiveStateReq
	(*SyncLiveStateResp)(nil),            // 12: SyncLiveStateResp
	(*SyncVideoStateReq)(nil),            // 13: SyncVideoStateReq
	(*CanRecommendVideo)(nil),            // 14: CanRecommendVideo
	(*SyncVideoStateResp)(nil),           // 15: SyncVideoStateResp
	(*DeleteVideoReq)(nil),               // 16: DeleteVideoReq
	(*DeleteVideoResp)(nil),              // 17: DeleteVideoResp
}
var file_recommend_recommend_proto_depIdxs = []int32{
	0,  // 0: CollectUserBehaviorReq.behavior_type:type_name -> BehaviorType
	14, // 1: SyncVideoStateReq.can_recommend_video_id:type_name -> CanRecommendVideo
	1,  // 2: RecommendService.CollectUserBehavior:input_type -> CollectUserBehaviorReq
	3,  // 3: RecommendService.CollectUserHistoryTag:input_type -> CollectUserHistoryTagReq
	5,  // 4: RecommendService.GetRecommendListByUserID:input_type -> GetRecommendListByUserIDReq
	7,  // 5: RecommendService.GetLives:input_type -> GetLivesReq
	9,  // 6: RecommendService.GetVideos:input_type -> GetVideosReq
	11, // 7: RecommendService.SyncLiveState:input_type -> SyncLiveStateReq
	13, // 8: RecommendService.SyncVideoState:input_type -> SyncVideoStateReq
	16, // 9: RecommendService.DeleteVideo:input_type -> DeleteVideoReq
	2,  // 10: RecommendService.CollectUserBehavior:output_type -> CollectUserBehaviorResp
	4,  // 11: RecommendService.CollectUserHistoryTag:output_type -> CollectUserHistoryTagResp
	6,  // 12: RecommendService.GetRecommendListByUserID:output_type -> GetRecommendListByUserIDResp
	8,  // 13: RecommendService.GetLives:output_type -> GetLivesResp
	10, // 14: RecommendService.GetVideos:output_type -> GetVideosResp
	12, // 15: RecommendService.SyncLiveState:output_type -> SyncLiveStateResp
	15, // 16: RecommendService.SyncVideoState:output_type -> SyncVideoStateResp
	17, // 17: RecommendService.DeleteVideo:output_type -> DeleteVideoResp
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_recommend_recommend_proto_init() }
func file_recommend_recommend_proto_init() {
	if File_recommend_recommend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recommend_recommend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectUserBehaviorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectUserBehaviorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectUserHistoryTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectUserHistoryTagResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecommendListByUserIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecommendListByUserIDResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLivesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLivesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideosResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncLiveStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncLiveStateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncVideoStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanRecommendVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncVideoStateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVideoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_recommend_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteVideoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recommend_recommend_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommend_recommend_proto_goTypes,
		DependencyIndexes: file_recommend_recommend_proto_depIdxs,
		EnumInfos:         file_recommend_recommend_proto_enumTypes,
		MessageInfos:      file_recommend_recommend_proto_msgTypes,
	}.Build()
	File_recommend_recommend_proto = out.File
	file_recommend_recommend_proto_rawDesc = nil
	file_recommend_recommend_proto_goTypes = nil
	file_recommend_recommend_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RecommendServiceClient is the client API for RecommendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecommendServiceClient interface {
	// 收集用户行为
	CollectUserBehavior(ctx context.Context, in *CollectUserBehaviorReq, opts ...grpc.CallOption) (*CollectUserBehaviorResp, error)
	// 收集用户历史浏览内容的一级标签, 后面会做多个标签,所以命名就是CollectUserHistoryTag
	CollectUserHistoryTag(ctx context.Context, in *CollectUserHistoryTagReq, opts ...grpc.CallOption) (*CollectUserHistoryTagResp, error)
	// 获取推荐列表
	GetRecommendListByUserID(ctx context.Context, in *GetRecommendListByUserIDReq, opts ...grpc.CallOption) (*GetRecommendListByUserIDResp, error)
	GetLives(ctx context.Context, in *GetLivesReq, opts ...grpc.CallOption) (*GetLivesResp, error)
	GetVideos(ctx context.Context, in *GetVideosReq, opts ...grpc.CallOption) (*GetVideosResp, error)
	SyncLiveState(ctx context.Context, in *SyncLiveStateReq, opts ...grpc.CallOption) (*SyncLiveStateResp, error)
	SyncVideoState(ctx context.Context, in *SyncVideoStateReq, opts ...grpc.CallOption) (*SyncVideoStateResp, error)
	DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error)
}

type recommendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendServiceClient(cc grpc.ClientConnInterface) RecommendServiceClient {
	return &recommendServiceClient{cc}
}

func (c *recommendServiceClient) CollectUserBehavior(ctx context.Context, in *CollectUserBehaviorReq, opts ...grpc.CallOption) (*CollectUserBehaviorResp, error) {
	out := new(CollectUserBehaviorResp)
	err := c.cc.Invoke(ctx, "/RecommendService/CollectUserBehavior", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) CollectUserHistoryTag(ctx context.Context, in *CollectUserHistoryTagReq, opts ...grpc.CallOption) (*CollectUserHistoryTagResp, error) {
	out := new(CollectUserHistoryTagResp)
	err := c.cc.Invoke(ctx, "/RecommendService/CollectUserHistoryTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) GetRecommendListByUserID(ctx context.Context, in *GetRecommendListByUserIDReq, opts ...grpc.CallOption) (*GetRecommendListByUserIDResp, error) {
	out := new(GetRecommendListByUserIDResp)
	err := c.cc.Invoke(ctx, "/RecommendService/GetRecommendListByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) GetLives(ctx context.Context, in *GetLivesReq, opts ...grpc.CallOption) (*GetLivesResp, error) {
	out := new(GetLivesResp)
	err := c.cc.Invoke(ctx, "/RecommendService/GetLives", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) GetVideos(ctx context.Context, in *GetVideosReq, opts ...grpc.CallOption) (*GetVideosResp, error) {
	out := new(GetVideosResp)
	err := c.cc.Invoke(ctx, "/RecommendService/GetVideos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) SyncLiveState(ctx context.Context, in *SyncLiveStateReq, opts ...grpc.CallOption) (*SyncLiveStateResp, error) {
	out := new(SyncLiveStateResp)
	err := c.cc.Invoke(ctx, "/RecommendService/SyncLiveState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) SyncVideoState(ctx context.Context, in *SyncVideoStateReq, opts ...grpc.CallOption) (*SyncVideoStateResp, error) {
	out := new(SyncVideoStateResp)
	err := c.cc.Invoke(ctx, "/RecommendService/SyncVideoState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) DeleteVideo(ctx context.Context, in *DeleteVideoReq, opts ...grpc.CallOption) (*DeleteVideoResp, error) {
	out := new(DeleteVideoResp)
	err := c.cc.Invoke(ctx, "/RecommendService/DeleteVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendServiceServer is the server API for RecommendService service.
type RecommendServiceServer interface {
	// 收集用户行为
	CollectUserBehavior(context.Context, *CollectUserBehaviorReq) (*CollectUserBehaviorResp, error)
	// 收集用户历史浏览内容的一级标签, 后面会做多个标签,所以命名就是CollectUserHistoryTag
	CollectUserHistoryTag(context.Context, *CollectUserHistoryTagReq) (*CollectUserHistoryTagResp, error)
	// 获取推荐列表
	GetRecommendListByUserID(context.Context, *GetRecommendListByUserIDReq) (*GetRecommendListByUserIDResp, error)
	GetLives(context.Context, *GetLivesReq) (*GetLivesResp, error)
	GetVideos(context.Context, *GetVideosReq) (*GetVideosResp, error)
	SyncLiveState(context.Context, *SyncLiveStateReq) (*SyncLiveStateResp, error)
	SyncVideoState(context.Context, *SyncVideoStateReq) (*SyncVideoStateResp, error)
	DeleteVideo(context.Context, *DeleteVideoReq) (*DeleteVideoResp, error)
}

// UnimplementedRecommendServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRecommendServiceServer struct {
}

func (*UnimplementedRecommendServiceServer) CollectUserBehavior(context.Context, *CollectUserBehaviorReq) (*CollectUserBehaviorResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectUserBehavior not implemented")
}
func (*UnimplementedRecommendServiceServer) CollectUserHistoryTag(context.Context, *CollectUserHistoryTagReq) (*CollectUserHistoryTagResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectUserHistoryTag not implemented")
}
func (*UnimplementedRecommendServiceServer) GetRecommendListByUserID(context.Context, *GetRecommendListByUserIDReq) (*GetRecommendListByUserIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendListByUserID not implemented")
}
func (*UnimplementedRecommendServiceServer) GetLives(context.Context, *GetLivesReq) (*GetLivesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLives not implemented")
}
func (*UnimplementedRecommendServiceServer) GetVideos(context.Context, *GetVideosReq) (*GetVideosResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideos not implemented")
}
func (*UnimplementedRecommendServiceServer) SyncLiveState(context.Context, *SyncLiveStateReq) (*SyncLiveStateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncLiveState not implemented")
}
func (*UnimplementedRecommendServiceServer) SyncVideoState(context.Context, *SyncVideoStateReq) (*SyncVideoStateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncVideoState not implemented")
}
func (*UnimplementedRecommendServiceServer) DeleteVideo(context.Context, *DeleteVideoReq) (*DeleteVideoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVideo not implemented")
}

func RegisterRecommendServiceServer(s *grpc.Server, srv RecommendServiceServer) {
	s.RegisterService(&_RecommendService_serviceDesc, srv)
}

func _RecommendService_CollectUserBehavior_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectUserBehaviorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).CollectUserBehavior(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendService/CollectUserBehavior",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).CollectUserBehavior(ctx, req.(*CollectUserBehaviorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_CollectUserHistoryTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectUserHistoryTagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).CollectUserHistoryTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendService/CollectUserHistoryTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).CollectUserHistoryTag(ctx, req.(*CollectUserHistoryTagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_GetRecommendListByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendListByUserIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).GetRecommendListByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendService/GetRecommendListByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).GetRecommendListByUserID(ctx, req.(*GetRecommendListByUserIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_GetLives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLivesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).GetLives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendService/GetLives",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).GetLives(ctx, req.(*GetLivesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_GetVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).GetVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendService/GetVideos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).GetVideos(ctx, req.(*GetVideosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_SyncLiveState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncLiveStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).SyncLiveState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendService/SyncLiveState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).SyncLiveState(ctx, req.(*SyncLiveStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_SyncVideoState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncVideoStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).SyncVideoState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendService/SyncVideoState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).SyncVideoState(ctx, req.(*SyncVideoStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_DeleteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).DeleteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecommendService/DeleteVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).DeleteVideo(ctx, req.(*DeleteVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecommendService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RecommendService",
	HandlerType: (*RecommendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectUserBehavior",
			Handler:    _RecommendService_CollectUserBehavior_Handler,
		},
		{
			MethodName: "CollectUserHistoryTag",
			Handler:    _RecommendService_CollectUserHistoryTag_Handler,
		},
		{
			MethodName: "GetRecommendListByUserID",
			Handler:    _RecommendService_GetRecommendListByUserID_Handler,
		},
		{
			MethodName: "GetLives",
			Handler:    _RecommendService_GetLives_Handler,
		},
		{
			MethodName: "GetVideos",
			Handler:    _RecommendService_GetVideos_Handler,
		},
		{
			MethodName: "SyncLiveState",
			Handler:    _RecommendService_SyncLiveState_Handler,
		},
		{
			MethodName: "SyncVideoState",
			Handler:    _RecommendService_SyncVideoState_Handler,
		},
		{
			MethodName: "DeleteVideo",
			Handler:    _RecommendService_DeleteVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommend/recommend.proto",
}
